// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "svm_classifier_Block_preheader_0_proc1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic svm_classifier_Block_preheader_0_proc1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic svm_classifier_Block_preheader_0_proc1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> svm_classifier_Block_preheader_0_proc1::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> svm_classifier_Block_preheader_0_proc1::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> svm_classifier_Block_preheader_0_proc1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> svm_classifier_Block_preheader_0_proc1::ap_const_lv1_1 = "1";
const sc_lv<32> svm_classifier_Block_preheader_0_proc1::ap_const_lv32_1 = "1";
const sc_lv<19> svm_classifier_Block_preheader_0_proc1::ap_const_lv19_E758 = "1110011101011000";
const sc_lv<32> svm_classifier_Block_preheader_0_proc1::ap_const_lv32_12 = "10010";

svm_classifier_Block_preheader_0_proc1::svm_classifier_Block_preheader_0_proc1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_52);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_83 );

    SC_METHOD(thread_out_r);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( r_V_fu_266_p2 );

    SC_METHOD(thread_out_r_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_Val2_80_s_fu_257_p2);
    sensitive << ( tmp25_reg_291 );
    sensitive << ( tmp_fu_253_p2 );

    SC_METHOD(thread_r_V_fu_266_p2);
    sensitive << ( tmp_15_fu_262_p1 );

    SC_METHOD(thread_tmp18_fu_175_p2);
    sensitive << ( tmp20_fu_169_p2 );
    sensitive << ( tmp19_fu_163_p2 );

    SC_METHOD(thread_tmp19_fu_163_p2);
    sensitive << ( p_read );
    sensitive << ( p_read1 );

    SC_METHOD(thread_tmp20_fu_169_p2);
    sensitive << ( p_read2 );
    sensitive << ( p_read3 );

    SC_METHOD(thread_tmp21_fu_199_p2);
    sensitive << ( tmp23_fu_193_p2 );
    sensitive << ( tmp22_fu_181_p2 );

    SC_METHOD(thread_tmp22_fu_181_p2);
    sensitive << ( p_read4 );
    sensitive << ( p_read5 );

    SC_METHOD(thread_tmp23_fu_193_p2);
    sensitive << ( p_read6 );
    sensitive << ( tmp24_fu_187_p2 );

    SC_METHOD(thread_tmp24_fu_187_p2);
    sensitive << ( p_read7 );
    sensitive << ( p_read8 );

    SC_METHOD(thread_tmp25_fu_247_p2);
    sensitive << ( tmp29_fu_241_p2 );
    sensitive << ( tmp26_fu_217_p2 );

    SC_METHOD(thread_tmp26_fu_217_p2);
    sensitive << ( tmp28_fu_211_p2 );
    sensitive << ( tmp27_fu_205_p2 );

    SC_METHOD(thread_tmp27_fu_205_p2);
    sensitive << ( p_read9 );
    sensitive << ( p_read10 );

    SC_METHOD(thread_tmp28_fu_211_p2);
    sensitive << ( p_read11 );
    sensitive << ( p_read12 );

    SC_METHOD(thread_tmp29_fu_241_p2);
    sensitive << ( tmp31_fu_235_p2 );
    sensitive << ( tmp30_fu_223_p2 );

    SC_METHOD(thread_tmp30_fu_223_p2);
    sensitive << ( p_read13 );
    sensitive << ( p_read14 );

    SC_METHOD(thread_tmp31_fu_235_p2);
    sensitive << ( p_read15 );
    sensitive << ( tmp32_fu_229_p2 );

    SC_METHOD(thread_tmp32_fu_229_p2);
    sensitive << ( p_read16 );
    sensitive << ( p_read17 );

    SC_METHOD(thread_tmp_15_fu_262_p1);
    sensitive << ( p_Val2_80_s_fu_257_p2 );

    SC_METHOD(thread_tmp_fu_253_p2);
    sensitive << ( tmp18_reg_281 );
    sensitive << ( tmp21_reg_286 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_52 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "svm_classifier_Block_preheader_0_proc1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read3, "(port)p_read3");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, p_read6, "(port)p_read6");
    sc_trace(mVcdFile, p_read7, "(port)p_read7");
    sc_trace(mVcdFile, p_read8, "(port)p_read8");
    sc_trace(mVcdFile, p_read9, "(port)p_read9");
    sc_trace(mVcdFile, p_read10, "(port)p_read10");
    sc_trace(mVcdFile, p_read11, "(port)p_read11");
    sc_trace(mVcdFile, p_read12, "(port)p_read12");
    sc_trace(mVcdFile, p_read13, "(port)p_read13");
    sc_trace(mVcdFile, p_read14, "(port)p_read14");
    sc_trace(mVcdFile, p_read15, "(port)p_read15");
    sc_trace(mVcdFile, p_read16, "(port)p_read16");
    sc_trace(mVcdFile, p_read17, "(port)p_read17");
    sc_trace(mVcdFile, out_r, "(port)out_r");
    sc_trace(mVcdFile, out_r_ap_vld, "(port)out_r_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, tmp18_fu_175_p2, "tmp18_fu_175_p2");
    sc_trace(mVcdFile, tmp18_reg_281, "tmp18_reg_281");
    sc_trace(mVcdFile, ap_sig_52, "ap_sig_52");
    sc_trace(mVcdFile, tmp21_fu_199_p2, "tmp21_fu_199_p2");
    sc_trace(mVcdFile, tmp21_reg_286, "tmp21_reg_286");
    sc_trace(mVcdFile, tmp25_fu_247_p2, "tmp25_fu_247_p2");
    sc_trace(mVcdFile, tmp25_reg_291, "tmp25_reg_291");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_83, "ap_sig_83");
    sc_trace(mVcdFile, tmp20_fu_169_p2, "tmp20_fu_169_p2");
    sc_trace(mVcdFile, tmp19_fu_163_p2, "tmp19_fu_163_p2");
    sc_trace(mVcdFile, tmp24_fu_187_p2, "tmp24_fu_187_p2");
    sc_trace(mVcdFile, tmp23_fu_193_p2, "tmp23_fu_193_p2");
    sc_trace(mVcdFile, tmp22_fu_181_p2, "tmp22_fu_181_p2");
    sc_trace(mVcdFile, tmp28_fu_211_p2, "tmp28_fu_211_p2");
    sc_trace(mVcdFile, tmp27_fu_205_p2, "tmp27_fu_205_p2");
    sc_trace(mVcdFile, tmp32_fu_229_p2, "tmp32_fu_229_p2");
    sc_trace(mVcdFile, tmp31_fu_235_p2, "tmp31_fu_235_p2");
    sc_trace(mVcdFile, tmp30_fu_223_p2, "tmp30_fu_223_p2");
    sc_trace(mVcdFile, tmp29_fu_241_p2, "tmp29_fu_241_p2");
    sc_trace(mVcdFile, tmp26_fu_217_p2, "tmp26_fu_217_p2");
    sc_trace(mVcdFile, tmp_fu_253_p2, "tmp_fu_253_p2");
    sc_trace(mVcdFile, p_Val2_80_s_fu_257_p2, "p_Val2_80_s_fu_257_p2");
    sc_trace(mVcdFile, tmp_15_fu_262_p1, "tmp_15_fu_262_p1");
    sc_trace(mVcdFile, r_V_fu_266_p2, "r_V_fu_266_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

svm_classifier_Block_preheader_0_proc1::~svm_classifier_Block_preheader_0_proc1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void svm_classifier_Block_preheader_0_proc1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_52.read())) {
        tmp18_reg_281 = tmp18_fu_175_p2.read();
        tmp21_reg_286 = tmp21_fu_199_p2.read();
        tmp25_reg_291 = tmp25_fu_247_p2.read();
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_sig_52() {
    ap_sig_52 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_sig_83() {
    ap_sig_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_83.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_out_r() {
    out_r = r_V_fu_266_p2.read().range(18, 18);
}

void svm_classifier_Block_preheader_0_proc1::thread_out_r_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        out_r_ap_vld = ap_const_logic_1;
    } else {
        out_r_ap_vld = ap_const_logic_0;
    }
}

void svm_classifier_Block_preheader_0_proc1::thread_p_Val2_80_s_fu_257_p2() {
    p_Val2_80_s_fu_257_p2 = (!tmp25_reg_291.read().is_01() || !tmp_fu_253_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp25_reg_291.read()) + sc_biguint<18>(tmp_fu_253_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_r_V_fu_266_p2() {
    r_V_fu_266_p2 = (!tmp_15_fu_262_p1.read().is_01() || !ap_const_lv19_E758.is_01())? sc_lv<19>(): (sc_bigint<19>(tmp_15_fu_262_p1.read()) + sc_biguint<19>(ap_const_lv19_E758));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp18_fu_175_p2() {
    tmp18_fu_175_p2 = (!tmp20_fu_169_p2.read().is_01() || !tmp19_fu_163_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp20_fu_169_p2.read()) + sc_biguint<18>(tmp19_fu_163_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp19_fu_163_p2() {
    tmp19_fu_163_p2 = (!p_read.read().is_01() || !p_read1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read.read()) + sc_biguint<18>(p_read1.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp20_fu_169_p2() {
    tmp20_fu_169_p2 = (!p_read2.read().is_01() || !p_read3.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read2.read()) + sc_biguint<18>(p_read3.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp21_fu_199_p2() {
    tmp21_fu_199_p2 = (!tmp23_fu_193_p2.read().is_01() || !tmp22_fu_181_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp23_fu_193_p2.read()) + sc_biguint<18>(tmp22_fu_181_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp22_fu_181_p2() {
    tmp22_fu_181_p2 = (!p_read4.read().is_01() || !p_read5.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read4.read()) + sc_biguint<18>(p_read5.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp23_fu_193_p2() {
    tmp23_fu_193_p2 = (!tmp24_fu_187_p2.read().is_01() || !p_read6.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp24_fu_187_p2.read()) + sc_biguint<18>(p_read6.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp24_fu_187_p2() {
    tmp24_fu_187_p2 = (!p_read7.read().is_01() || !p_read8.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read7.read()) + sc_biguint<18>(p_read8.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp25_fu_247_p2() {
    tmp25_fu_247_p2 = (!tmp29_fu_241_p2.read().is_01() || !tmp26_fu_217_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp29_fu_241_p2.read()) + sc_biguint<18>(tmp26_fu_217_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp26_fu_217_p2() {
    tmp26_fu_217_p2 = (!tmp28_fu_211_p2.read().is_01() || !tmp27_fu_205_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp28_fu_211_p2.read()) + sc_biguint<18>(tmp27_fu_205_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp27_fu_205_p2() {
    tmp27_fu_205_p2 = (!p_read9.read().is_01() || !p_read10.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read9.read()) + sc_biguint<18>(p_read10.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp28_fu_211_p2() {
    tmp28_fu_211_p2 = (!p_read11.read().is_01() || !p_read12.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read11.read()) + sc_biguint<18>(p_read12.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp29_fu_241_p2() {
    tmp29_fu_241_p2 = (!tmp31_fu_235_p2.read().is_01() || !tmp30_fu_223_p2.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp31_fu_235_p2.read()) + sc_biguint<18>(tmp30_fu_223_p2.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp30_fu_223_p2() {
    tmp30_fu_223_p2 = (!p_read13.read().is_01() || !p_read14.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read13.read()) + sc_biguint<18>(p_read14.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp31_fu_235_p2() {
    tmp31_fu_235_p2 = (!tmp32_fu_229_p2.read().is_01() || !p_read15.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp32_fu_229_p2.read()) + sc_biguint<18>(p_read15.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp32_fu_229_p2() {
    tmp32_fu_229_p2 = (!p_read16.read().is_01() || !p_read17.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_read16.read()) + sc_biguint<18>(p_read17.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp_15_fu_262_p1() {
    tmp_15_fu_262_p1 = esl_sext<19,18>(p_Val2_80_s_fu_257_p2.read());
}

void svm_classifier_Block_preheader_0_proc1::thread_tmp_fu_253_p2() {
    tmp_fu_253_p2 = (!tmp21_reg_286.read().is_01() || !tmp18_reg_281.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp21_reg_286.read()) + sc_biguint<18>(tmp18_reg_281.read()));
}

void svm_classifier_Block_preheader_0_proc1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_52.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

