// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_H__
#define __svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 13;
  static const unsigned AddressRange = 117;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_ram) {
        for (unsigned i = 0; i < 11 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[11] = "0b1100000110110";
        ram[12] = "0b0000010000101";
        ram[13] = "0b1110111101011";
        ram[14] = "0b0000010000101";
        ram[15] = "0b0000010000101";
        ram[16] = "0b0000010000101";
        ram[17] = "0b1111001110010";
        for (unsigned i = 18; i < 29 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[29] = "0b1110101100110";
        ram[30] = "0b0000010000101";
        ram[31] = "0b1111101111010";
        ram[32] = "0b1111101111010";
        for (unsigned i = 33; i < 47 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[47] = "0b1101001000111";
        for (unsigned i = 48; i < 54 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[54] = "0b1001011111110";
        ram[55] = "0b1111011110101";
        for (unsigned i = 56; i < 78 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[78] = "0b1111101111010";
        ram[79] = "0b0000010000101";
        ram[80] = "0b0000010000101";
        ram[81] = "0b0000010000101";
        ram[82] = "0b1111011110101";
        for (unsigned i = 83; i < 91 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[91] = "0b1111001110010";
        ram[92] = "0b0000010000101";
        ram[93] = "0b1111101111010";
        ram[94] = "0b0000010000101";
        ram[95] = "0b1111101111010";
        ram[96] = "0b1111101111010";
        for (unsigned i = 97; i < 104 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[104] = "0b1111101111010";
        ram[105] = "0b0000010000101";
        ram[106] = "0b0000010000101";
        ram[107] = "0b0000010000101";
        ram[108] = "0b0000010000101";
        ram[109] = "0b1111101111010";
        for (unsigned i = 110; i < 116 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[116] = "0b1111011110101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(svm_classifier_Loop_Sum_loop_proc1_alpha_V_0) {


static const unsigned DataWidth = 13;
static const unsigned AddressRange = 117;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_ram* meminst;


SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_0) {
meminst = new svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_ram("svm_classifier_Loop_Sum_loop_proc1_alpha_V_0_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~svm_classifier_Loop_Sum_loop_proc1_alpha_V_0() {
    delete meminst;
}


};//endmodule
#endif
