// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _svm_classifier_HH_
#define _svm_classifier_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "svm_classifier_svm_classifier_entry3.h"
#include "svm_classifier_Block_proc.h"
#include "svm_classifier_Loop_Sum_loop_proc1.h"
#include "svm_classifier_Block_preheader_0_proc1.h"
#include "FIFO_svm_classifier_in_V_channel.h"
#include "FIFO_svm_classifier_s_in_0_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_1_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_2_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_3_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_4_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_5_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_6_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_7_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_8_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_9_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_10_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_11_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_12_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_13_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_14_V_loc_channel.h"
#include "FIFO_svm_classifier_s_in_15_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_V_8_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_V_7_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_V_6_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_0_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_1_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_2_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_3_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_4_V_loc_channel.h"
#include "FIFO_svm_classifier_ch_sums_5_V_loc_channel.h"
#include "svm_classifier_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct svm_classifier : public sc_module {
    // Port declarations 20
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    svm_classifier(sc_module_name name);
    SC_HAS_PROCESS(svm_classifier);

    ~svm_classifier();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    svm_classifier_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* svm_classifier_AXILiteS_s_axi_U;
    svm_classifier_svm_classifier_entry3* svm_classifier_svm_classifier_entry3_U0;
    svm_classifier_Block_proc* svm_classifier_Block_proc_U0;
    svm_classifier_Loop_Sum_loop_proc1* svm_classifier_Loop_Sum_loop_proc1_U0;
    svm_classifier_Block_preheader_0_proc1* svm_classifier_Block_preheader_0_proc1_U0;
    FIFO_svm_classifier_in_V_channel* in_V_channel_U;
    FIFO_svm_classifier_s_in_0_V_loc_channel* s_in_0_V_loc_channel_U;
    FIFO_svm_classifier_s_in_1_V_loc_channel* s_in_1_V_loc_channel_U;
    FIFO_svm_classifier_s_in_2_V_loc_channel* s_in_2_V_loc_channel_U;
    FIFO_svm_classifier_s_in_3_V_loc_channel* s_in_3_V_loc_channel_U;
    FIFO_svm_classifier_s_in_4_V_loc_channel* s_in_4_V_loc_channel_U;
    FIFO_svm_classifier_s_in_5_V_loc_channel* s_in_5_V_loc_channel_U;
    FIFO_svm_classifier_s_in_6_V_loc_channel* s_in_6_V_loc_channel_U;
    FIFO_svm_classifier_s_in_7_V_loc_channel* s_in_7_V_loc_channel_U;
    FIFO_svm_classifier_s_in_8_V_loc_channel* s_in_8_V_loc_channel_U;
    FIFO_svm_classifier_s_in_9_V_loc_channel* s_in_9_V_loc_channel_U;
    FIFO_svm_classifier_s_in_10_V_loc_channel* s_in_10_V_loc_channel_U;
    FIFO_svm_classifier_s_in_11_V_loc_channel* s_in_11_V_loc_channel_U;
    FIFO_svm_classifier_s_in_12_V_loc_channel* s_in_12_V_loc_channel_U;
    FIFO_svm_classifier_s_in_13_V_loc_channel* s_in_13_V_loc_channel_U;
    FIFO_svm_classifier_s_in_14_V_loc_channel* s_in_14_V_loc_channel_U;
    FIFO_svm_classifier_s_in_15_V_loc_channel* s_in_15_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_V_8_loc_channel* ch_sums_V_8_loc_channel_U;
    FIFO_svm_classifier_ch_sums_V_7_loc_channel* ch_sums_V_7_loc_channel_U;
    FIFO_svm_classifier_ch_sums_V_6_loc_channel* ch_sums_V_6_loc_channel_U;
    FIFO_svm_classifier_ch_sums_0_V_loc_channel* ch_sums_0_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_1_V_loc_channel* ch_sums_1_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_2_V_loc_channel* ch_sums_2_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_3_V_loc_channel* ch_sums_3_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_4_V_loc_channel* ch_sums_4_V_loc_channel_U;
    FIFO_svm_classifier_ch_sums_5_V_loc_channel* ch_sums_5_V_loc_channel_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<256> > in_V;
    sc_signal< sc_logic > out_r;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_ap_start;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_ap_done;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_ap_continue;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_ap_idle;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_ap_ready;
    sc_signal< sc_lv<256> > svm_classifier_svm_classifier_entry3_U0_in_V_out_din;
    sc_signal< sc_logic > svm_classifier_svm_classifier_entry3_U0_in_V_out_write;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_ap_start;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_ap_done;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_ap_continue;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_ap_idle;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_ap_ready;
    sc_signal< sc_logic > svm_classifier_Block_proc_U0_in_V_read;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_0;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_1;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_2;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_3;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_4;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_5;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_6;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_7;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_8;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_9;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_10;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_11;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_12;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_13;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_14;
    sc_signal< sc_lv<13> > svm_classifier_Block_proc_U0_ap_return_15;
    sc_signal< sc_logic > s_in_15_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_15_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_15_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_15_V_loc_channel;
    sc_signal< sc_logic > s_in_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_5_V_loc_channel;
    sc_signal< sc_logic > s_in_14_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_14_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_14_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_14_V_loc_channel;
    sc_signal< sc_logic > s_in_9_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_9_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_9_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_9_V_loc_channel;
    sc_signal< sc_logic > s_in_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_3_V_loc_channel;
    sc_signal< sc_logic > s_in_10_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_10_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_10_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_10_V_loc_channel;
    sc_signal< sc_logic > s_in_7_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_7_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_7_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_7_V_loc_channel;
    sc_signal< sc_logic > s_in_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_1_V_loc_channel;
    sc_signal< sc_logic > s_in_6_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_6_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_6_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_6_V_loc_channel;
    sc_signal< sc_logic > s_in_13_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_13_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_13_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_13_V_loc_channel;
    sc_signal< sc_logic > s_in_11_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_11_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_11_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_11_V_loc_channel;
    sc_signal< sc_logic > s_in_8_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_8_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_8_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_8_V_loc_channel;
    sc_signal< sc_logic > s_in_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_4_V_loc_channel;
    sc_signal< sc_logic > s_in_12_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_12_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_12_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_12_V_loc_channel;
    sc_signal< sc_logic > s_in_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_0_V_loc_channel;
    sc_signal< sc_logic > s_in_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_s_in_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_s_in_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Block_proc_U0_s_in_2_V_loc_channel;
    sc_signal< sc_logic > svm_classifier_Loop_Sum_loop_proc1_U0_ap_start;
    sc_signal< sc_logic > svm_classifier_Loop_Sum_loop_proc1_U0_ap_done;
    sc_signal< sc_logic > svm_classifier_Loop_Sum_loop_proc1_U0_ap_continue;
    sc_signal< sc_logic > svm_classifier_Loop_Sum_loop_proc1_U0_ap_idle;
    sc_signal< sc_logic > svm_classifier_Loop_Sum_loop_proc1_U0_ap_ready;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_0;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_1;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_2;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_3;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_4;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_5;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_6;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_7;
    sc_signal< sc_lv<18> > svm_classifier_Loop_Sum_loop_proc1_U0_ap_return_8;
    sc_signal< sc_logic > ch_sums_V_8_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_V_8_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_V_8_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_8_loc_channel;
    sc_signal< sc_logic > ch_sums_V_6_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_V_6_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_V_6_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_6_loc_channel;
    sc_signal< sc_logic > ch_sums_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_3_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_3_V_loc_channel;
    sc_signal< sc_logic > ch_sums_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_5_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_5_V_loc_channel;
    sc_signal< sc_logic > ch_sums_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_4_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_4_V_loc_channel;
    sc_signal< sc_logic > ch_sums_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_2_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_2_V_loc_channel;
    sc_signal< sc_logic > ch_sums_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_1_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_1_V_loc_channel;
    sc_signal< sc_logic > ch_sums_V_7_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_V_7_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_V_7_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_7_loc_channel;
    sc_signal< sc_logic > ch_sums_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_reg_ch_sums_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_sig_ch_sums_0_V_loc_channel_full_n;
    sc_signal< sc_logic > ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_0_V_loc_channel;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_ap_start;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_ap_done;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_ap_continue;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_ap_idle;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_ap_ready;
    sc_signal< sc_lv<1> > svm_classifier_Block_preheader_0_proc1_U0_out_r;
    sc_signal< sc_logic > svm_classifier_Block_preheader_0_proc1_U0_out_r_ap_vld;
    sc_signal< sc_logic > ap_sig_hs_continue;
    sc_signal< sc_logic > in_V_channel_full_n;
    sc_signal< sc_lv<256> > in_V_channel_dout;
    sc_signal< sc_logic > in_V_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_0_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_0_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_1_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_1_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_2_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_2_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_3_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_3_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_4_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_4_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_5_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_5_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_6_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_6_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_7_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_7_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_8_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_8_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_9_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_9_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_10_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_10_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_11_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_11_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_12_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_12_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_13_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_13_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_14_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_14_V_loc_channel_empty_n;
    sc_signal< sc_lv<13> > s_in_15_V_loc_channel_dout;
    sc_signal< sc_logic > s_in_15_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_V_8_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_V_8_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_V_7_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_V_7_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_V_6_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_V_6_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_0_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_0_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_1_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_1_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_2_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_2_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_3_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_3_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_4_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_4_V_loc_channel_empty_n;
    sc_signal< sc_lv<18> > ch_sums_5_V_loc_channel_dout;
    sc_signal< sc_logic > ch_sums_5_V_loc_channel_empty_n;
    sc_signal< sc_logic > ap_sig_hs_done;
    sc_signal< sc_logic > ap_sig_hs_ready;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_true;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_0_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_10_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_11_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_12_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_13_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_14_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_15_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_1_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_2_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_3_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_4_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_5_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_6_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_7_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_8_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Block_proc_U0_s_in_9_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_0_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_1_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_2_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_3_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_4_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_5_V_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_6_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_7_loc_channel();
    void thread_ap_chn_write_svm_classifier_Loop_Sum_loop_proc1_U0_ch_sums_V_8_loc_channel();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_ch_sums_0_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_1_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_2_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_3_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_4_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_5_V_loc_channel_full_n();
    void thread_ap_sig_ch_sums_V_6_loc_channel_full_n();
    void thread_ap_sig_ch_sums_V_7_loc_channel_full_n();
    void thread_ap_sig_ch_sums_V_8_loc_channel_full_n();
    void thread_ap_sig_hs_continue();
    void thread_ap_sig_hs_done();
    void thread_ap_sig_hs_ready();
    void thread_ap_sig_s_in_0_V_loc_channel_full_n();
    void thread_ap_sig_s_in_10_V_loc_channel_full_n();
    void thread_ap_sig_s_in_11_V_loc_channel_full_n();
    void thread_ap_sig_s_in_12_V_loc_channel_full_n();
    void thread_ap_sig_s_in_13_V_loc_channel_full_n();
    void thread_ap_sig_s_in_14_V_loc_channel_full_n();
    void thread_ap_sig_s_in_15_V_loc_channel_full_n();
    void thread_ap_sig_s_in_1_V_loc_channel_full_n();
    void thread_ap_sig_s_in_2_V_loc_channel_full_n();
    void thread_ap_sig_s_in_3_V_loc_channel_full_n();
    void thread_ap_sig_s_in_4_V_loc_channel_full_n();
    void thread_ap_sig_s_in_5_V_loc_channel_full_n();
    void thread_ap_sig_s_in_6_V_loc_channel_full_n();
    void thread_ap_sig_s_in_7_V_loc_channel_full_n();
    void thread_ap_sig_s_in_8_V_loc_channel_full_n();
    void thread_ap_sig_s_in_9_V_loc_channel_full_n();
    void thread_out_r();
    void thread_svm_classifier_Block_preheader_0_proc1_U0_ap_continue();
    void thread_svm_classifier_Block_preheader_0_proc1_U0_ap_start();
    void thread_svm_classifier_Block_proc_U0_ap_continue();
    void thread_svm_classifier_Loop_Sum_loop_proc1_U0_ap_continue();
    void thread_svm_classifier_Loop_Sum_loop_proc1_U0_ap_start();
    void thread_svm_classifier_svm_classifier_entry3_U0_ap_continue();
    void thread_svm_classifier_svm_classifier_entry3_U0_ap_start();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
