// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "svm_classifier_getTanh.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic svm_classifier_getTanh::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic svm_classifier_getTanh::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> svm_classifier_getTanh::ap_ST_pp0_stg0_fsm_0 = "1";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> svm_classifier_getTanh::ap_const_lv1_1 = "1";
const sc_lv<1> svm_classifier_getTanh::ap_const_lv1_0 = "0";
const sc_lv<8> svm_classifier_getTanh::ap_const_lv8_20 = "100000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_F = "1111";
const sc_lv<16> svm_classifier_getTanh::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> svm_classifier_getTanh::ap_const_lv16_A00 = "101000000000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_9 = "1001";
const sc_lv<9> svm_classifier_getTanh::ap_const_lv9_0 = "000000000";
const sc_lv<7> svm_classifier_getTanh::ap_const_lv7_1 = "1";
const sc_lv<3> svm_classifier_getTanh::ap_const_lv3_0 = "000";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_7F737 = "1111111011100110111";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_8C9 = "100011001001";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_12 = "10010";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_3 = "11";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_7FBEA = "1111111101111101010";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_416 = "10000010110";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_7FDFE = "1111111110111111110";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_202 = "1000000010";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_1657 = "1011001010111";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_9A8 = "100110101000";
const sc_lv<11> svm_classifier_getTanh::ap_const_lv11_595 = "10110010101";
const sc_lv<11> svm_classifier_getTanh::ap_const_lv11_26A = "1001101010";
const sc_lv<11> svm_classifier_getTanh::ap_const_lv11_596 = "10110010110";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_1351 = "1001101010001";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_1B2B = "1101100101011";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_4D4 = "10011010100";
const sc_lv<13> svm_classifier_getTanh::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_C = "1100";
const sc_lv<14> svm_classifier_getTanh::ap_const_lv14_0 = "00000000000000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_D = "1101";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_7FF00 = "1111111111100000000";
const sc_lv<21> svm_classifier_getTanh::ap_const_lv21_100 = "100000000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_4 = "100";
const sc_lv<15> svm_classifier_getTanh::ap_const_lv15_0 = "000000000000000";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_E = "1110";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_5 = "101";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_2 = "10";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_11 = "10001";
const sc_lv<32> svm_classifier_getTanh::ap_const_lv32_7 = "111";
const sc_lv<5> svm_classifier_getTanh::ap_const_lv5_0 = "00000";
const sc_lv<8> svm_classifier_getTanh::ap_const_lv8_0 = "00000000";
const bool svm_classifier_getTanh::ap_true = true;

svm_classifier_getTanh::svm_classifier_getTanh(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sinh_lut_V_U = new svm_classifier_getTanh_sinh_lut_V("sinh_lut_V_U");
    sinh_lut_V_U->clk(ap_clk);
    sinh_lut_V_U->reset(ap_rst);
    sinh_lut_V_U->address0(sinh_lut_V_address0);
    sinh_lut_V_U->ce0(sinh_lut_V_ce0);
    sinh_lut_V_U->q0(sinh_lut_V_q0);
    cosh_lut_V_U = new svm_classifier_getTanh_cosh_lut_V("cosh_lut_V_U");
    cosh_lut_V_U->clk(ap_clk);
    cosh_lut_V_U->reset(ap_rst);
    cosh_lut_V_U->address0(cosh_lut_V_address0);
    cosh_lut_V_U->ce0(cosh_lut_V_ce0);
    cosh_lut_V_U->q0(cosh_lut_V_q0);
    svm_classifier_mul_10s_9ns_19_1_U0 = new svm_classifier_mul_10s_9ns_19_1<1,1,10,9,19>("svm_classifier_mul_10s_9ns_19_1_U0");
    svm_classifier_mul_10s_9ns_19_1_U0->din0(p_Val2_3_fu_931_p0);
    svm_classifier_mul_10s_9ns_19_1_U0->din1(p_Val2_3_fu_931_p1);
    svm_classifier_mul_10s_9ns_19_1_U0->dout(p_Val2_3_fu_931_p2);
    svm_classifier_mul_10s_9ns_19_1_U1 = new svm_classifier_mul_10s_9ns_19_1<1,1,10,9,19>("svm_classifier_mul_10s_9ns_19_1_U1");
    svm_classifier_mul_10s_9ns_19_1_U1->din0(p_Val2_4_fu_961_p0);
    svm_classifier_mul_10s_9ns_19_1_U1->din1(p_Val2_4_fu_961_p1);
    svm_classifier_mul_10s_9ns_19_1_U1->dout(p_Val2_4_fu_961_p2);
    svm_classifier_mul_10s_9ns_19_1_U2 = new svm_classifier_mul_10s_9ns_19_1<1,1,10,9,19>("svm_classifier_mul_10s_9ns_19_1_U2");
    svm_classifier_mul_10s_9ns_19_1_U2->din0(p_Val2_5_fu_981_p0);
    svm_classifier_mul_10s_9ns_19_1_U2->din1(p_Val2_5_fu_981_p1);
    svm_classifier_mul_10s_9ns_19_1_U2->dout(p_Val2_5_fu_981_p2);
    svm_classifier_mul_10s_9ns_19_1_U3 = new svm_classifier_mul_10s_9ns_19_1<1,1,10,9,19>("svm_classifier_mul_10s_9ns_19_1_U3");
    svm_classifier_mul_10s_9ns_19_1_U3->din0(p_Val2_6_fu_997_p0);
    svm_classifier_mul_10s_9ns_19_1_U3->din1(p_Val2_6_fu_997_p1);
    svm_classifier_mul_10s_9ns_19_1_U3->dout(p_Val2_6_fu_997_p2);
    svm_classifier_sdiv_13ns_8s_13_17_U4 = new svm_classifier_sdiv_13ns_8s_13_17<1,17,13,8,13>("svm_classifier_sdiv_13ns_8s_13_17_U4");
    svm_classifier_sdiv_13ns_8s_13_17_U4->clk(ap_clk);
    svm_classifier_sdiv_13ns_8s_13_17_U4->reset(ap_rst);
    svm_classifier_sdiv_13ns_8s_13_17_U4->din0(grp_fu_1053_p0);
    svm_classifier_sdiv_13ns_8s_13_17_U4->din1(cosh_out_V_fu_1021_p4);
    svm_classifier_sdiv_13ns_8s_13_17_U4->ce(ap_var_for_const0);
    svm_classifier_sdiv_13ns_8s_13_17_U4->dout(grp_fu_1053_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_1_cast_fu_977_p1);
    sensitive << ( cosh_lut_V_q0 );

    SC_METHOD(thread_OP1_V_cast_fu_923_p1);
    sensitive << ( sinh_lut_V_q0 );

    SC_METHOD(thread_OP2_V_18_1_fu_414_p3);
    sensitive << ( tmp_408_reg_1097 );

    SC_METHOD(thread_OP2_V_19_2_cast_fu_505_p1);
    sensitive << ( p_Val2_111_1_fu_439_p2 );

    SC_METHOD(thread_OP2_V_19_3_cast_cast_fu_562_p1);
    sensitive << ( p_Val2_111_2_fu_499_p2 );

    SC_METHOD(thread_OP2_V_1_cast_fu_957_p1);
    sensitive << ( tmp_28_fu_947_p4 );

    SC_METHOD(thread_OP2_V_cast_fu_927_p1);
    sensitive << ( tmp_25_fu_913_p4 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it21 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppiten_pp0_it12 );
    sensitive << ( ap_reg_ppiten_pp0_it13 );
    sensitive << ( ap_reg_ppiten_pp0_it14 );
    sensitive << ( ap_reg_ppiten_pp0_it15 );
    sensitive << ( ap_reg_ppiten_pp0_it16 );
    sensitive << ( ap_reg_ppiten_pp0_it17 );
    sensitive << ( ap_reg_ppiten_pp0_it18 );
    sensitive << ( ap_reg_ppiten_pp0_it19 );
    sensitive << ( ap_reg_ppiten_pp0_it20 );
    sensitive << ( ap_reg_ppiten_pp0_it21 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1);

    SC_METHOD(thread_ap_reg_ppiten_pp0_it0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it21 );
    sensitive << ( ap_reg_ppstg_neg_reg_1077_pp0_iter20 );
    sensitive << ( p_Val2_11_phi_fu_180_p4 );
    sensitive << ( p_Val2_47_fu_1064_p2 );

    SC_METHOD(thread_ap_sig_18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_311);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_0);
    sensitive << ( ap_sig_18 );

    SC_METHOD(thread_ap_sig_pprstidle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it6 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_reg_ppiten_pp0_it8 );
    sensitive << ( ap_reg_ppiten_pp0_it9 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppiten_pp0_it12 );
    sensitive << ( ap_reg_ppiten_pp0_it13 );
    sensitive << ( ap_reg_ppiten_pp0_it14 );
    sensitive << ( ap_reg_ppiten_pp0_it15 );
    sensitive << ( ap_reg_ppiten_pp0_it16 );
    sensitive << ( ap_reg_ppiten_pp0_it17 );
    sensitive << ( ap_reg_ppiten_pp0_it18 );
    sensitive << ( ap_reg_ppiten_pp0_it19 );
    sensitive << ( ap_reg_ppiten_pp0_it20 );

    SC_METHOD(thread_cosh_lut_V_address0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_23_fu_840_p1 );

    SC_METHOD(thread_cosh_lut_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_cosh_out_V_fu_1021_p4);
    sensitive << ( tmp_305_fu_1017_p2 );

    SC_METHOD(thread_grp_fu_1053_p0);
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( tmp_306_fu_1031_p4 );

    SC_METHOD(thread_mf15_2_fu_509_p2);
    sensitive << ( OP2_V_19_2_cast_fu_505_p1 );

    SC_METHOD(thread_mf15_3_fu_566_p2);
    sensitive << ( OP2_V_19_3_cast_cast_fu_562_p1 );

    SC_METHOD(thread_mf15_4_fu_785_p2);
    sensitive << ( p_Val2_111_3_fu_693_p2 );

    SC_METHOD(thread_mf15_5_fu_834_p2);
    sensitive << ( p_Val2_111_4_fu_779_p2 );

    SC_METHOD(thread_mf_1_fu_421_p3);
    sensitive << ( tmp_408_reg_1097 );

    SC_METHOD(thread_mf_2_fu_462_p2);
    sensitive << ( p_Val2_114_1_fu_452_p2 );

    SC_METHOD(thread_mf_3_fu_556_p2);
    sensitive << ( p_Val2_114_2_fu_550_p2 );

    SC_METHOD(thread_mf_4_fu_742_p2);
    sensitive << ( p_Val2_114_3_fu_736_p2 );

    SC_METHOD(thread_mf_5_fu_828_p2);
    sensitive << ( p_Val2_114_4_fu_822_p2 );

    SC_METHOD(thread_neg_fu_187_p3);
    sensitive << ( theta_in_V );

    SC_METHOD(thread_p_1_fu_257_p3);
    sensitive << ( ret_V_fu_215_p4 );
    sensitive << ( tmp_406_fu_225_p3 );
    sensitive << ( p_s_fu_249_p3 );

    SC_METHOD(thread_p_Val2_111_1_fu_439_p2);
    sensitive << ( tmp_127_1_cast_fu_435_p1 );

    SC_METHOD(thread_p_Val2_111_2_cast2_fu_658_p1);
    sensitive << ( p_Val2_111_2_reg_1128 );

    SC_METHOD(thread_p_Val2_111_2_fu_499_p2);
    sensitive << ( p_Val2_111_1_fu_439_p2 );
    sensitive << ( tmp_1304_2_cast_fu_495_p1 );

    SC_METHOD(thread_p_Val2_111_3_fu_693_p2);
    sensitive << ( p_Val2_111_2_cast2_fu_658_p1 );
    sensitive << ( tmp_1304_3_cast_fu_689_p1 );

    SC_METHOD(thread_p_Val2_111_4_fu_779_p2);
    sensitive << ( p_Val2_111_3_fu_693_p2 );
    sensitive << ( tmp_1304_4_cast_fu_775_p1 );

    SC_METHOD(thread_p_Val2_111_5_fu_874_p2);
    sensitive << ( p_Val2_111_4_reg_1162 );
    sensitive << ( tmp_1304_5_cast_fu_870_p1 );

    SC_METHOD(thread_p_Val2_114_1_cast_cast_fu_458_p1);
    sensitive << ( p_Val2_114_1_fu_452_p2 );

    SC_METHOD(thread_p_Val2_114_1_fu_452_p2);
    sensitive << ( tmp_385_fu_407_p3 );
    sensitive << ( tmp_1356_1_cast_cast_fu_445_p3 );

    SC_METHOD(thread_p_Val2_114_2_cast1_fu_661_p1);
    sensitive << ( p_Val2_114_2_reg_1134 );

    SC_METHOD(thread_p_Val2_114_2_fu_550_p2);
    sensitive << ( p_Val2_114_1_cast_cast_fu_458_p1 );
    sensitive << ( tmp_1356_2_cast_fu_546_p1 );

    SC_METHOD(thread_p_Val2_114_3_fu_736_p2);
    sensitive << ( p_Val2_114_2_cast1_fu_661_p1 );
    sensitive << ( tmp_1356_3_cast_fu_732_p1 );

    SC_METHOD(thread_p_Val2_114_4_fu_822_p2);
    sensitive << ( p_Val2_114_3_fu_736_p2 );
    sensitive << ( tmp_1356_4_cast_fu_818_p1 );

    SC_METHOD(thread_p_Val2_114_5_fu_908_p2);
    sensitive << ( p_Val2_114_4_reg_1168 );
    sensitive << ( tmp_1356_5_cast_fu_904_p1 );

    SC_METHOD(thread_p_Val2_116_1_fu_349_p2);
    sensitive << ( tmp_140_1_cast_fu_337_p1 );
    sensitive << ( tmp_1418_1_cast_cast_fu_341_p3 );

    SC_METHOD(thread_p_Val2_116_2_fu_393_p2);
    sensitive << ( tmp_140_2_cast_fu_381_p1 );
    sensitive << ( tmp_1418_2_cast_cast_fu_385_p3 );

    SC_METHOD(thread_p_Val2_116_3_fu_600_p2);
    sensitive << ( tmp_140_3_cast_fu_589_p1 );
    sensitive << ( tmp_1418_3_cast_cast_fu_593_p3 );

    SC_METHOD(thread_p_Val2_116_4_fu_644_p2);
    sensitive << ( tmp_140_4_cast_fu_632_p1 );
    sensitive << ( tmp_1418_4_cast_cast_fu_636_p3 );

    SC_METHOD(thread_p_Val2_11_phi_fu_180_p4);
    sensitive << ( ap_reg_ppiten_pp0_it21 );
    sensitive << ( ap_reg_ppstg_tmp_s_reg_1087_pp0_iter20 );
    sensitive << ( pro_V_fu_1059_p1 );
    sensitive << ( ap_reg_phiprechg_p_Val2_11_reg_176pp0_it21 );

    SC_METHOD(thread_p_Val2_3_fu_931_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP2_V_cast_fu_927_p1 );

    SC_METHOD(thread_p_Val2_3_fu_931_p1);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP1_V_cast_fu_923_p1 );

    SC_METHOD(thread_p_Val2_46_fu_305_p2);
    sensitive << ( tmp_140_cast_fu_293_p1 );
    sensitive << ( tmp_450_cast_cast_fu_297_p3 );

    SC_METHOD(thread_p_Val2_47_fu_1064_p2);
    sensitive << ( p_Val2_11_phi_fu_180_p4 );

    SC_METHOD(thread_p_Val2_4_fu_961_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP2_V_1_cast_fu_957_p1 );

    SC_METHOD(thread_p_Val2_4_fu_961_p1);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP1_V_cast_fu_923_p1 );

    SC_METHOD(thread_p_Val2_5_fu_981_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP2_V_1_cast_fu_957_p1 );

    SC_METHOD(thread_p_Val2_5_fu_981_p1);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP1_V_1_cast_fu_977_p1 );

    SC_METHOD(thread_p_Val2_6_fu_997_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP2_V_cast_fu_927_p1 );

    SC_METHOD(thread_p_Val2_6_fu_997_p1);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( OP1_V_1_cast_fu_977_p1 );

    SC_METHOD(thread_p_Val2_s_54_fu_201_p3);
    sensitive << ( theta_in_V );
    sensitive << ( neg_fu_187_p3 );
    sensitive << ( p_Val2_s_fu_195_p2 );

    SC_METHOD(thread_p_Val2_s_fu_195_p2);
    sensitive << ( theta_in_V );

    SC_METHOD(thread_p_s_fu_249_p3);
    sensitive << ( ret_V_fu_215_p4 );
    sensitive << ( tmp_20_fu_237_p2 );
    sensitive << ( ret_V_1_fu_243_p2 );

    SC_METHOD(thread_p_v1_fu_811_p3);
    sensitive << ( tmp_422_reg_1150 );
    sensitive << ( tmp_426_fu_801_p4 );
    sensitive << ( tmp_425_fu_791_p4 );

    SC_METHOD(thread_p_v2_fu_863_p3);
    sensitive << ( ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3 );
    sensitive << ( tmp_429_fu_854_p4 );
    sensitive << ( tmp_428_fu_845_p4 );

    SC_METHOD(thread_p_v3_fu_897_p3);
    sensitive << ( ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3 );
    sensitive << ( tmp_431_fu_888_p4 );
    sensitive << ( tmp_430_fu_879_p4 );

    SC_METHOD(thread_p_v9_fu_768_p3);
    sensitive << ( tmp_422_reg_1150 );
    sensitive << ( tmp_424_fu_758_p4 );
    sensitive << ( tmp_423_fu_748_p4 );

    SC_METHOD(thread_p_v_fu_682_p3);
    sensitive << ( ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2 );
    sensitive << ( tmp_418_fu_673_p4 );
    sensitive << ( tmp_417_fu_664_p4 );

    SC_METHOD(thread_pro_V_fu_1059_p1);
    sensitive << ( grp_fu_1053_p2 );

    SC_METHOD(thread_ret_V_1_fu_243_p2);
    sensitive << ( ret_V_fu_215_p4 );

    SC_METHOD(thread_ret_V_fu_215_p4);
    sensitive << ( p_Val2_s_54_fu_201_p3 );

    SC_METHOD(thread_sinh_lut_V_address0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( tmp_23_fu_840_p1 );

    SC_METHOD(thread_sinh_lut_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );

    SC_METHOD(thread_theta_in_V_assign_fu_272_p2);
    sensitive << ( p_Val2_s_54_reg_1082 );
    sensitive << ( tmp_22_fu_265_p3 );

    SC_METHOD(thread_tmp_127_1_cast_fu_435_p1);
    sensitive << ( tmp_127_1_fu_428_p3 );

    SC_METHOD(thread_tmp_127_1_fu_428_p3);
    sensitive << ( tmp_409_reg_1104 );
    sensitive << ( mf_1_fu_421_p3 );
    sensitive << ( OP2_V_18_1_fu_414_p3 );

    SC_METHOD(thread_tmp_1304_2_cast_fu_495_p1);
    sensitive << ( tmp_413_fu_488_p3 );

    SC_METHOD(thread_tmp_1304_3_cast_fu_689_p1);
    sensitive << ( p_v_fu_682_p3 );

    SC_METHOD(thread_tmp_1304_4_cast_fu_775_p1);
    sensitive << ( p_v9_fu_768_p3 );

    SC_METHOD(thread_tmp_1304_5_cast_fu_870_p1);
    sensitive << ( p_v2_fu_863_p3 );

    SC_METHOD(thread_tmp_1356_1_cast_cast_fu_445_p3);
    sensitive << ( tmp_409_reg_1104 );

    SC_METHOD(thread_tmp_1356_2_cast_fu_546_p1);
    sensitive << ( tmp_415_fu_539_p3 );

    SC_METHOD(thread_tmp_1356_3_cast_fu_732_p1);
    sensitive << ( tmp_421_fu_725_p3 );

    SC_METHOD(thread_tmp_1356_4_cast_fu_818_p1);
    sensitive << ( p_v1_fu_811_p3 );

    SC_METHOD(thread_tmp_1356_5_cast_fu_904_p1);
    sensitive << ( p_v3_fu_897_p3 );

    SC_METHOD(thread_tmp_140_1_cast_fu_337_p1);
    sensitive << ( tmp_140_1_fu_329_p3 );

    SC_METHOD(thread_tmp_140_1_fu_329_p3);
    sensitive << ( tmp_269_fu_319_p4 );

    SC_METHOD(thread_tmp_140_2_cast_fu_381_p1);
    sensitive << ( tmp_140_2_fu_373_p3 );

    SC_METHOD(thread_tmp_140_2_fu_373_p3);
    sensitive << ( tmp_277_fu_363_p4 );

    SC_METHOD(thread_tmp_140_3_cast_fu_589_p1);
    sensitive << ( tmp_140_3_fu_581_p3 );

    SC_METHOD(thread_tmp_140_3_fu_581_p3);
    sensitive << ( tmp_286_fu_572_p4 );

    SC_METHOD(thread_tmp_140_4_cast_fu_632_p1);
    sensitive << ( tmp_140_4_fu_624_p3 );

    SC_METHOD(thread_tmp_140_4_fu_624_p3);
    sensitive << ( tmp_295_fu_614_p4 );

    SC_METHOD(thread_tmp_140_cast_fu_293_p1);
    sensitive << ( tmp_140_fu_285_p3 );

    SC_METHOD(thread_tmp_140_fu_285_p3);
    sensitive << ( theta_in_V_assign_fu_272_p2 );

    SC_METHOD(thread_tmp_1418_1_cast_cast_fu_341_p3);
    sensitive << ( tmp_409_fu_311_p3 );

    SC_METHOD(thread_tmp_1418_2_cast_cast_fu_385_p3);
    sensitive << ( tmp_410_fu_355_p3 );

    SC_METHOD(thread_tmp_1418_3_cast_cast_fu_593_p3);
    sensitive << ( tmp_416_reg_1121 );

    SC_METHOD(thread_tmp_1418_4_cast_cast_fu_636_p3);
    sensitive << ( tmp_422_fu_606_p3 );

    SC_METHOD(thread_tmp_20_fu_237_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_s_fu_209_p2 );
    sensitive << ( tmp_407_fu_233_p1 );

    SC_METHOD(thread_tmp_22_fu_265_p3);
    sensitive << ( p_1_reg_1091 );

    SC_METHOD(thread_tmp_23_fu_840_p1);
    sensitive << ( ap_reg_ppstg_p_1_reg_1091_pp0_iter2 );

    SC_METHOD(thread_tmp_25_fu_913_p4);
    sensitive << ( p_Val2_111_5_fu_874_p2 );

    SC_METHOD(thread_tmp_269_fu_319_p4);
    sensitive << ( p_Val2_46_fu_305_p2 );

    SC_METHOD(thread_tmp_273_fu_515_p4);
    sensitive << ( p_Val2_111_1_fu_439_p2 );

    SC_METHOD(thread_tmp_274_fu_525_p1);
    sensitive << ( tmp_273_fu_515_p4 );

    SC_METHOD(thread_tmp_277_fu_363_p4);
    sensitive << ( p_Val2_116_1_fu_349_p2 );

    SC_METHOD(thread_tmp_283_fu_708_p1);
    sensitive << ( tmp_419_fu_699_p4 );

    SC_METHOD(thread_tmp_284_fu_721_p1);
    sensitive << ( tmp_420_fu_712_p4 );

    SC_METHOD(thread_tmp_286_fu_572_p4);
    sensitive << ( p_Val2_116_2_reg_1116 );

    SC_METHOD(thread_tmp_28_fu_947_p4);
    sensitive << ( p_Val2_114_5_fu_908_p2 );

    SC_METHOD(thread_tmp_295_fu_614_p4);
    sensitive << ( p_Val2_116_3_fu_600_p2 );

    SC_METHOD(thread_tmp_304_fu_1013_p2);
    sensitive << ( sincos_V_reg_1194 );
    sensitive << ( cossin_V_reg_1204 );

    SC_METHOD(thread_tmp_305_fu_1017_p2);
    sensitive << ( sinsin_V_reg_1199 );
    sensitive << ( coscos_V_reg_1209 );

    SC_METHOD(thread_tmp_306_fu_1031_p4);
    sensitive << ( tmp_304_fu_1013_p2 );

    SC_METHOD(thread_tmp_385_fu_407_p3);
    sensitive << ( tmp_408_reg_1097 );

    SC_METHOD(thread_tmp_406_fu_225_p3);
    sensitive << ( p_Val2_s_54_fu_201_p3 );

    SC_METHOD(thread_tmp_407_fu_233_p1);
    sensitive << ( p_Val2_s_54_fu_201_p3 );

    SC_METHOD(thread_tmp_408_fu_277_p3);
    sensitive << ( theta_in_V_assign_fu_272_p2 );

    SC_METHOD(thread_tmp_409_fu_311_p3);
    sensitive << ( p_Val2_46_fu_305_p2 );

    SC_METHOD(thread_tmp_410_fu_355_p3);
    sensitive << ( p_Val2_116_1_fu_349_p2 );

    SC_METHOD(thread_tmp_411_fu_468_p4);
    sensitive << ( mf_2_fu_462_p2 );

    SC_METHOD(thread_tmp_412_fu_478_p4);
    sensitive << ( p_Val2_114_1_fu_452_p2 );

    SC_METHOD(thread_tmp_413_fu_488_p3);
    sensitive << ( tmp_410_reg_1110 );
    sensitive << ( tmp_411_fu_468_p4 );
    sensitive << ( tmp_412_fu_478_p4 );

    SC_METHOD(thread_tmp_414_fu_529_p4);
    sensitive << ( mf15_2_fu_509_p2 );

    SC_METHOD(thread_tmp_415_fu_539_p3);
    sensitive << ( tmp_410_reg_1110 );
    sensitive << ( tmp_414_fu_529_p4 );
    sensitive << ( tmp_274_fu_525_p1 );

    SC_METHOD(thread_tmp_417_fu_664_p4);
    sensitive << ( p_Val2_114_2_reg_1134 );

    SC_METHOD(thread_tmp_418_fu_673_p4);
    sensitive << ( mf_3_reg_1140 );

    SC_METHOD(thread_tmp_419_fu_699_p4);
    sensitive << ( p_Val2_111_2_reg_1128 );

    SC_METHOD(thread_tmp_420_fu_712_p4);
    sensitive << ( mf15_3_reg_1145 );

    SC_METHOD(thread_tmp_421_fu_725_p3);
    sensitive << ( ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2 );
    sensitive << ( tmp_284_fu_721_p1 );
    sensitive << ( tmp_283_fu_708_p1 );

    SC_METHOD(thread_tmp_422_fu_606_p3);
    sensitive << ( p_Val2_116_3_fu_600_p2 );

    SC_METHOD(thread_tmp_423_fu_748_p4);
    sensitive << ( p_Val2_114_3_fu_736_p2 );

    SC_METHOD(thread_tmp_424_fu_758_p4);
    sensitive << ( mf_4_fu_742_p2 );

    SC_METHOD(thread_tmp_425_fu_791_p4);
    sensitive << ( p_Val2_111_3_fu_693_p2 );

    SC_METHOD(thread_tmp_426_fu_801_p4);
    sensitive << ( mf15_4_fu_785_p2 );

    SC_METHOD(thread_tmp_428_fu_845_p4);
    sensitive << ( p_Val2_114_4_reg_1168 );

    SC_METHOD(thread_tmp_429_fu_854_p4);
    sensitive << ( mf_5_reg_1174 );

    SC_METHOD(thread_tmp_430_fu_879_p4);
    sensitive << ( p_Val2_111_4_reg_1162 );

    SC_METHOD(thread_tmp_431_fu_888_p4);
    sensitive << ( mf15_5_reg_1179 );

    SC_METHOD(thread_tmp_450_cast_cast_fu_297_p3);
    sensitive << ( tmp_408_fu_277_p3 );

    SC_METHOD(thread_tmp_s_fu_209_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( p_Val2_s_54_fu_201_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_pprstidle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it12 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it13 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it14 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it15 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it16 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it17 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it18 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it19 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it20 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it21 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "svm_classifier_getTanh_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, theta_in_V, "(port)theta_in_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_0, "ap_sig_cseq_ST_pp0_stg0_fsm_0");
    sc_trace(mVcdFile, ap_sig_18, "ap_sig_18");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it12, "ap_reg_ppiten_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it13, "ap_reg_ppiten_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it14, "ap_reg_ppiten_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it15, "ap_reg_ppiten_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it16, "ap_reg_ppiten_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it17, "ap_reg_ppiten_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it18, "ap_reg_ppiten_pp0_it18");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it19, "ap_reg_ppiten_pp0_it19");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it20, "ap_reg_ppiten_pp0_it20");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it21, "ap_reg_ppiten_pp0_it21");
    sc_trace(mVcdFile, sinh_lut_V_address0, "sinh_lut_V_address0");
    sc_trace(mVcdFile, sinh_lut_V_ce0, "sinh_lut_V_ce0");
    sc_trace(mVcdFile, sinh_lut_V_q0, "sinh_lut_V_q0");
    sc_trace(mVcdFile, cosh_lut_V_address0, "cosh_lut_V_address0");
    sc_trace(mVcdFile, cosh_lut_V_ce0, "cosh_lut_V_ce0");
    sc_trace(mVcdFile, cosh_lut_V_q0, "cosh_lut_V_q0");
    sc_trace(mVcdFile, neg_fu_187_p3, "neg_fu_187_p3");
    sc_trace(mVcdFile, neg_reg_1077, "neg_reg_1077");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter1, "ap_reg_ppstg_neg_reg_1077_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter2, "ap_reg_ppstg_neg_reg_1077_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter3, "ap_reg_ppstg_neg_reg_1077_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter4, "ap_reg_ppstg_neg_reg_1077_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter5, "ap_reg_ppstg_neg_reg_1077_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter6, "ap_reg_ppstg_neg_reg_1077_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter7, "ap_reg_ppstg_neg_reg_1077_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter8, "ap_reg_ppstg_neg_reg_1077_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter9, "ap_reg_ppstg_neg_reg_1077_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter10, "ap_reg_ppstg_neg_reg_1077_pp0_iter10");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter11, "ap_reg_ppstg_neg_reg_1077_pp0_iter11");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter12, "ap_reg_ppstg_neg_reg_1077_pp0_iter12");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter13, "ap_reg_ppstg_neg_reg_1077_pp0_iter13");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter14, "ap_reg_ppstg_neg_reg_1077_pp0_iter14");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter15, "ap_reg_ppstg_neg_reg_1077_pp0_iter15");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter16, "ap_reg_ppstg_neg_reg_1077_pp0_iter16");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter17, "ap_reg_ppstg_neg_reg_1077_pp0_iter17");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter18, "ap_reg_ppstg_neg_reg_1077_pp0_iter18");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter19, "ap_reg_ppstg_neg_reg_1077_pp0_iter19");
    sc_trace(mVcdFile, ap_reg_ppstg_neg_reg_1077_pp0_iter20, "ap_reg_ppstg_neg_reg_1077_pp0_iter20");
    sc_trace(mVcdFile, p_Val2_s_54_fu_201_p3, "p_Val2_s_54_fu_201_p3");
    sc_trace(mVcdFile, p_Val2_s_54_reg_1082, "p_Val2_s_54_reg_1082");
    sc_trace(mVcdFile, tmp_s_fu_209_p2, "tmp_s_fu_209_p2");
    sc_trace(mVcdFile, tmp_s_reg_1087, "tmp_s_reg_1087");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter3, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter4, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter5, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter6, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter7, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter8, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter9, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter10, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter10");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter11, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter11");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter12, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter12");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter13, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter13");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter14, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter14");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter15, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter15");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter16, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter16");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter17, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter17");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter18, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter18");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter19, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter19");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_s_reg_1087_pp0_iter20, "ap_reg_ppstg_tmp_s_reg_1087_pp0_iter20");
    sc_trace(mVcdFile, p_1_fu_257_p3, "p_1_fu_257_p3");
    sc_trace(mVcdFile, p_1_reg_1091, "p_1_reg_1091");
    sc_trace(mVcdFile, ap_reg_ppstg_p_1_reg_1091_pp0_iter1, "ap_reg_ppstg_p_1_reg_1091_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_p_1_reg_1091_pp0_iter2, "ap_reg_ppstg_p_1_reg_1091_pp0_iter2");
    sc_trace(mVcdFile, tmp_408_fu_277_p3, "tmp_408_fu_277_p3");
    sc_trace(mVcdFile, tmp_408_reg_1097, "tmp_408_reg_1097");
    sc_trace(mVcdFile, tmp_409_fu_311_p3, "tmp_409_fu_311_p3");
    sc_trace(mVcdFile, tmp_409_reg_1104, "tmp_409_reg_1104");
    sc_trace(mVcdFile, tmp_410_fu_355_p3, "tmp_410_fu_355_p3");
    sc_trace(mVcdFile, tmp_410_reg_1110, "tmp_410_reg_1110");
    sc_trace(mVcdFile, p_Val2_116_2_fu_393_p2, "p_Val2_116_2_fu_393_p2");
    sc_trace(mVcdFile, p_Val2_116_2_reg_1116, "p_Val2_116_2_reg_1116");
    sc_trace(mVcdFile, tmp_416_reg_1121, "tmp_416_reg_1121");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2, "ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2");
    sc_trace(mVcdFile, p_Val2_111_2_fu_499_p2, "p_Val2_111_2_fu_499_p2");
    sc_trace(mVcdFile, p_Val2_111_2_reg_1128, "p_Val2_111_2_reg_1128");
    sc_trace(mVcdFile, p_Val2_114_2_fu_550_p2, "p_Val2_114_2_fu_550_p2");
    sc_trace(mVcdFile, p_Val2_114_2_reg_1134, "p_Val2_114_2_reg_1134");
    sc_trace(mVcdFile, mf_3_fu_556_p2, "mf_3_fu_556_p2");
    sc_trace(mVcdFile, mf_3_reg_1140, "mf_3_reg_1140");
    sc_trace(mVcdFile, mf15_3_fu_566_p2, "mf15_3_fu_566_p2");
    sc_trace(mVcdFile, mf15_3_reg_1145, "mf15_3_reg_1145");
    sc_trace(mVcdFile, tmp_422_fu_606_p3, "tmp_422_fu_606_p3");
    sc_trace(mVcdFile, tmp_422_reg_1150, "tmp_422_reg_1150");
    sc_trace(mVcdFile, tmp_427_reg_1156, "tmp_427_reg_1156");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3, "ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3");
    sc_trace(mVcdFile, p_Val2_111_4_fu_779_p2, "p_Val2_111_4_fu_779_p2");
    sc_trace(mVcdFile, p_Val2_111_4_reg_1162, "p_Val2_111_4_reg_1162");
    sc_trace(mVcdFile, p_Val2_114_4_fu_822_p2, "p_Val2_114_4_fu_822_p2");
    sc_trace(mVcdFile, p_Val2_114_4_reg_1168, "p_Val2_114_4_reg_1168");
    sc_trace(mVcdFile, mf_5_fu_828_p2, "mf_5_fu_828_p2");
    sc_trace(mVcdFile, mf_5_reg_1174, "mf_5_reg_1174");
    sc_trace(mVcdFile, mf15_5_fu_834_p2, "mf15_5_fu_834_p2");
    sc_trace(mVcdFile, mf15_5_reg_1179, "mf15_5_reg_1179");
    sc_trace(mVcdFile, sincos_V_reg_1194, "sincos_V_reg_1194");
    sc_trace(mVcdFile, sinsin_V_reg_1199, "sinsin_V_reg_1199");
    sc_trace(mVcdFile, cossin_V_reg_1204, "cossin_V_reg_1204");
    sc_trace(mVcdFile, coscos_V_reg_1209, "coscos_V_reg_1209");
    sc_trace(mVcdFile, pro_V_fu_1059_p1, "pro_V_fu_1059_p1");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it21, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it21");
    sc_trace(mVcdFile, p_Val2_11_phi_fu_180_p4, "p_Val2_11_phi_fu_180_p4");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it2, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it2");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it3, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it3");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it4, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it4");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it5, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it5");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it6, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it6");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it7, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it7");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it8, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it8");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it9, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it9");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it10, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it10");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it11, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it11");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it12, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it12");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it13, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it13");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it14, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it14");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it15, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it15");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it16, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it16");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it17, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it17");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it18, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it18");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it19, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it19");
    sc_trace(mVcdFile, ap_reg_phiprechg_p_Val2_11_reg_176pp0_it20, "ap_reg_phiprechg_p_Val2_11_reg_176pp0_it20");
    sc_trace(mVcdFile, tmp_23_fu_840_p1, "tmp_23_fu_840_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_195_p2, "p_Val2_s_fu_195_p2");
    sc_trace(mVcdFile, tmp_407_fu_233_p1, "tmp_407_fu_233_p1");
    sc_trace(mVcdFile, ret_V_fu_215_p4, "ret_V_fu_215_p4");
    sc_trace(mVcdFile, tmp_20_fu_237_p2, "tmp_20_fu_237_p2");
    sc_trace(mVcdFile, ret_V_1_fu_243_p2, "ret_V_1_fu_243_p2");
    sc_trace(mVcdFile, tmp_406_fu_225_p3, "tmp_406_fu_225_p3");
    sc_trace(mVcdFile, p_s_fu_249_p3, "p_s_fu_249_p3");
    sc_trace(mVcdFile, tmp_22_fu_265_p3, "tmp_22_fu_265_p3");
    sc_trace(mVcdFile, theta_in_V_assign_fu_272_p2, "theta_in_V_assign_fu_272_p2");
    sc_trace(mVcdFile, tmp_140_fu_285_p3, "tmp_140_fu_285_p3");
    sc_trace(mVcdFile, tmp_140_cast_fu_293_p1, "tmp_140_cast_fu_293_p1");
    sc_trace(mVcdFile, tmp_450_cast_cast_fu_297_p3, "tmp_450_cast_cast_fu_297_p3");
    sc_trace(mVcdFile, p_Val2_46_fu_305_p2, "p_Val2_46_fu_305_p2");
    sc_trace(mVcdFile, tmp_269_fu_319_p4, "tmp_269_fu_319_p4");
    sc_trace(mVcdFile, tmp_140_1_fu_329_p3, "tmp_140_1_fu_329_p3");
    sc_trace(mVcdFile, tmp_140_1_cast_fu_337_p1, "tmp_140_1_cast_fu_337_p1");
    sc_trace(mVcdFile, tmp_1418_1_cast_cast_fu_341_p3, "tmp_1418_1_cast_cast_fu_341_p3");
    sc_trace(mVcdFile, p_Val2_116_1_fu_349_p2, "p_Val2_116_1_fu_349_p2");
    sc_trace(mVcdFile, tmp_277_fu_363_p4, "tmp_277_fu_363_p4");
    sc_trace(mVcdFile, tmp_140_2_fu_373_p3, "tmp_140_2_fu_373_p3");
    sc_trace(mVcdFile, tmp_140_2_cast_fu_381_p1, "tmp_140_2_cast_fu_381_p1");
    sc_trace(mVcdFile, tmp_1418_2_cast_cast_fu_385_p3, "tmp_1418_2_cast_cast_fu_385_p3");
    sc_trace(mVcdFile, mf_1_fu_421_p3, "mf_1_fu_421_p3");
    sc_trace(mVcdFile, OP2_V_18_1_fu_414_p3, "OP2_V_18_1_fu_414_p3");
    sc_trace(mVcdFile, tmp_127_1_fu_428_p3, "tmp_127_1_fu_428_p3");
    sc_trace(mVcdFile, tmp_127_1_cast_fu_435_p1, "tmp_127_1_cast_fu_435_p1");
    sc_trace(mVcdFile, tmp_385_fu_407_p3, "tmp_385_fu_407_p3");
    sc_trace(mVcdFile, tmp_1356_1_cast_cast_fu_445_p3, "tmp_1356_1_cast_cast_fu_445_p3");
    sc_trace(mVcdFile, p_Val2_114_1_fu_452_p2, "p_Val2_114_1_fu_452_p2");
    sc_trace(mVcdFile, mf_2_fu_462_p2, "mf_2_fu_462_p2");
    sc_trace(mVcdFile, tmp_411_fu_468_p4, "tmp_411_fu_468_p4");
    sc_trace(mVcdFile, tmp_412_fu_478_p4, "tmp_412_fu_478_p4");
    sc_trace(mVcdFile, tmp_413_fu_488_p3, "tmp_413_fu_488_p3");
    sc_trace(mVcdFile, p_Val2_111_1_fu_439_p2, "p_Val2_111_1_fu_439_p2");
    sc_trace(mVcdFile, tmp_1304_2_cast_fu_495_p1, "tmp_1304_2_cast_fu_495_p1");
    sc_trace(mVcdFile, OP2_V_19_2_cast_fu_505_p1, "OP2_V_19_2_cast_fu_505_p1");
    sc_trace(mVcdFile, tmp_273_fu_515_p4, "tmp_273_fu_515_p4");
    sc_trace(mVcdFile, mf15_2_fu_509_p2, "mf15_2_fu_509_p2");
    sc_trace(mVcdFile, tmp_414_fu_529_p4, "tmp_414_fu_529_p4");
    sc_trace(mVcdFile, tmp_274_fu_525_p1, "tmp_274_fu_525_p1");
    sc_trace(mVcdFile, tmp_415_fu_539_p3, "tmp_415_fu_539_p3");
    sc_trace(mVcdFile, p_Val2_114_1_cast_cast_fu_458_p1, "p_Val2_114_1_cast_cast_fu_458_p1");
    sc_trace(mVcdFile, tmp_1356_2_cast_fu_546_p1, "tmp_1356_2_cast_fu_546_p1");
    sc_trace(mVcdFile, OP2_V_19_3_cast_cast_fu_562_p1, "OP2_V_19_3_cast_cast_fu_562_p1");
    sc_trace(mVcdFile, tmp_286_fu_572_p4, "tmp_286_fu_572_p4");
    sc_trace(mVcdFile, tmp_140_3_fu_581_p3, "tmp_140_3_fu_581_p3");
    sc_trace(mVcdFile, tmp_140_3_cast_fu_589_p1, "tmp_140_3_cast_fu_589_p1");
    sc_trace(mVcdFile, tmp_1418_3_cast_cast_fu_593_p3, "tmp_1418_3_cast_cast_fu_593_p3");
    sc_trace(mVcdFile, p_Val2_116_3_fu_600_p2, "p_Val2_116_3_fu_600_p2");
    sc_trace(mVcdFile, tmp_295_fu_614_p4, "tmp_295_fu_614_p4");
    sc_trace(mVcdFile, tmp_140_4_fu_624_p3, "tmp_140_4_fu_624_p3");
    sc_trace(mVcdFile, tmp_140_4_cast_fu_632_p1, "tmp_140_4_cast_fu_632_p1");
    sc_trace(mVcdFile, tmp_1418_4_cast_cast_fu_636_p3, "tmp_1418_4_cast_cast_fu_636_p3");
    sc_trace(mVcdFile, p_Val2_116_4_fu_644_p2, "p_Val2_116_4_fu_644_p2");
    sc_trace(mVcdFile, tmp_418_fu_673_p4, "tmp_418_fu_673_p4");
    sc_trace(mVcdFile, tmp_417_fu_664_p4, "tmp_417_fu_664_p4");
    sc_trace(mVcdFile, p_v_fu_682_p3, "p_v_fu_682_p3");
    sc_trace(mVcdFile, p_Val2_111_2_cast2_fu_658_p1, "p_Val2_111_2_cast2_fu_658_p1");
    sc_trace(mVcdFile, tmp_1304_3_cast_fu_689_p1, "tmp_1304_3_cast_fu_689_p1");
    sc_trace(mVcdFile, tmp_419_fu_699_p4, "tmp_419_fu_699_p4");
    sc_trace(mVcdFile, tmp_420_fu_712_p4, "tmp_420_fu_712_p4");
    sc_trace(mVcdFile, tmp_284_fu_721_p1, "tmp_284_fu_721_p1");
    sc_trace(mVcdFile, tmp_283_fu_708_p1, "tmp_283_fu_708_p1");
    sc_trace(mVcdFile, tmp_421_fu_725_p3, "tmp_421_fu_725_p3");
    sc_trace(mVcdFile, p_Val2_114_2_cast1_fu_661_p1, "p_Val2_114_2_cast1_fu_661_p1");
    sc_trace(mVcdFile, tmp_1356_3_cast_fu_732_p1, "tmp_1356_3_cast_fu_732_p1");
    sc_trace(mVcdFile, p_Val2_114_3_fu_736_p2, "p_Val2_114_3_fu_736_p2");
    sc_trace(mVcdFile, mf_4_fu_742_p2, "mf_4_fu_742_p2");
    sc_trace(mVcdFile, tmp_424_fu_758_p4, "tmp_424_fu_758_p4");
    sc_trace(mVcdFile, tmp_423_fu_748_p4, "tmp_423_fu_748_p4");
    sc_trace(mVcdFile, p_v9_fu_768_p3, "p_v9_fu_768_p3");
    sc_trace(mVcdFile, p_Val2_111_3_fu_693_p2, "p_Val2_111_3_fu_693_p2");
    sc_trace(mVcdFile, tmp_1304_4_cast_fu_775_p1, "tmp_1304_4_cast_fu_775_p1");
    sc_trace(mVcdFile, mf15_4_fu_785_p2, "mf15_4_fu_785_p2");
    sc_trace(mVcdFile, tmp_426_fu_801_p4, "tmp_426_fu_801_p4");
    sc_trace(mVcdFile, tmp_425_fu_791_p4, "tmp_425_fu_791_p4");
    sc_trace(mVcdFile, p_v1_fu_811_p3, "p_v1_fu_811_p3");
    sc_trace(mVcdFile, tmp_1356_4_cast_fu_818_p1, "tmp_1356_4_cast_fu_818_p1");
    sc_trace(mVcdFile, tmp_429_fu_854_p4, "tmp_429_fu_854_p4");
    sc_trace(mVcdFile, tmp_428_fu_845_p4, "tmp_428_fu_845_p4");
    sc_trace(mVcdFile, p_v2_fu_863_p3, "p_v2_fu_863_p3");
    sc_trace(mVcdFile, tmp_1304_5_cast_fu_870_p1, "tmp_1304_5_cast_fu_870_p1");
    sc_trace(mVcdFile, tmp_431_fu_888_p4, "tmp_431_fu_888_p4");
    sc_trace(mVcdFile, tmp_430_fu_879_p4, "tmp_430_fu_879_p4");
    sc_trace(mVcdFile, p_v3_fu_897_p3, "p_v3_fu_897_p3");
    sc_trace(mVcdFile, tmp_1356_5_cast_fu_904_p1, "tmp_1356_5_cast_fu_904_p1");
    sc_trace(mVcdFile, p_Val2_111_5_fu_874_p2, "p_Val2_111_5_fu_874_p2");
    sc_trace(mVcdFile, tmp_25_fu_913_p4, "tmp_25_fu_913_p4");
    sc_trace(mVcdFile, p_Val2_3_fu_931_p0, "p_Val2_3_fu_931_p0");
    sc_trace(mVcdFile, OP2_V_cast_fu_927_p1, "OP2_V_cast_fu_927_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_931_p1, "p_Val2_3_fu_931_p1");
    sc_trace(mVcdFile, OP1_V_cast_fu_923_p1, "OP1_V_cast_fu_923_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_931_p2, "p_Val2_3_fu_931_p2");
    sc_trace(mVcdFile, p_Val2_114_5_fu_908_p2, "p_Val2_114_5_fu_908_p2");
    sc_trace(mVcdFile, tmp_28_fu_947_p4, "tmp_28_fu_947_p4");
    sc_trace(mVcdFile, p_Val2_4_fu_961_p0, "p_Val2_4_fu_961_p0");
    sc_trace(mVcdFile, OP2_V_1_cast_fu_957_p1, "OP2_V_1_cast_fu_957_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_961_p1, "p_Val2_4_fu_961_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_961_p2, "p_Val2_4_fu_961_p2");
    sc_trace(mVcdFile, p_Val2_5_fu_981_p0, "p_Val2_5_fu_981_p0");
    sc_trace(mVcdFile, p_Val2_5_fu_981_p1, "p_Val2_5_fu_981_p1");
    sc_trace(mVcdFile, OP1_V_1_cast_fu_977_p1, "OP1_V_1_cast_fu_977_p1");
    sc_trace(mVcdFile, p_Val2_5_fu_981_p2, "p_Val2_5_fu_981_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_997_p0, "p_Val2_6_fu_997_p0");
    sc_trace(mVcdFile, p_Val2_6_fu_997_p1, "p_Val2_6_fu_997_p1");
    sc_trace(mVcdFile, p_Val2_6_fu_997_p2, "p_Val2_6_fu_997_p2");
    sc_trace(mVcdFile, tmp_305_fu_1017_p2, "tmp_305_fu_1017_p2");
    sc_trace(mVcdFile, tmp_304_fu_1013_p2, "tmp_304_fu_1013_p2");
    sc_trace(mVcdFile, tmp_306_fu_1031_p4, "tmp_306_fu_1031_p4");
    sc_trace(mVcdFile, cosh_out_V_fu_1021_p4, "cosh_out_V_fu_1021_p4");
    sc_trace(mVcdFile, grp_fu_1053_p0, "grp_fu_1053_p0");
    sc_trace(mVcdFile, grp_fu_1053_p2, "grp_fu_1053_p2");
    sc_trace(mVcdFile, p_Val2_47_fu_1064_p2, "p_Val2_47_fu_1064_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_pprstidle_pp0, "ap_sig_pprstidle_pp0");
    sc_trace(mVcdFile, ap_sig_311, "ap_sig_311");
#endif

    }
}

svm_classifier_getTanh::~svm_classifier_getTanh() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sinh_lut_V_U;
    delete cosh_lut_V_U;
    delete svm_classifier_mul_10s_9ns_19_1_U0;
    delete svm_classifier_mul_10s_9ns_19_1_U1;
    delete svm_classifier_mul_10s_9ns_19_1_U2;
    delete svm_classifier_mul_10s_9ns_19_1_U3;
    delete svm_classifier_sdiv_13ns_8s_13_17_U4;
}

void svm_classifier_getTanh::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void svm_classifier_getTanh::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_pp0_stg0_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (ap_sig_311.read()) {
        if (esl_seteq<1,1,1>(tmp_s_reg_1087.read(), ap_const_lv1_0)) {
            ap_reg_phiprechg_p_Val2_11_reg_176pp0_it2 = ap_const_lv8_20;
        } else if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_phiprechg_p_Val2_11_reg_176pp0_it2 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it12 = ap_reg_ppiten_pp0_it11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it13 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it13 = ap_reg_ppiten_pp0_it12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it14 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it14 = ap_reg_ppiten_pp0_it13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it15 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it15 = ap_reg_ppiten_pp0_it14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it16 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it16 = ap_reg_ppiten_pp0_it15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it17 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it17 = ap_reg_ppiten_pp0_it16.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it18 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it18 = ap_reg_ppiten_pp0_it17.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it19 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it19 = ap_reg_ppiten_pp0_it18.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it20 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it20 = ap_reg_ppiten_pp0_it19.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it21 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it21 = ap_reg_ppiten_pp0_it20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it10 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it9.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it11 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it10.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it12 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it11.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it12.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it13 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it12.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it13.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it14 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it13.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it14.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it15 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it14.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it15.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it16 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it15.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it16.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it17 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it16.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it17.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it18 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it17.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it18.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it19 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it18.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it19.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it20 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it19.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it20.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it21 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it20.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it3 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it4 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it5 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it4.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it6 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it7 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it8 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it7.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it8.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_phiprechg_p_Val2_11_reg_176pp0_it9 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it8.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_reg_ppstg_neg_reg_1077_pp0_iter1 = neg_reg_1077.read();
        ap_reg_ppstg_p_1_reg_1091_pp0_iter1 = p_1_reg_1091.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1 = tmp_s_reg_1087.read();
        neg_reg_1077 = theta_in_V.read().range(15, 15);
        p_Val2_s_54_reg_1082 = p_Val2_s_54_fu_201_p3.read();
        tmp_s_reg_1087 = tmp_s_fu_209_p2.read();
    }
    if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        ap_reg_ppstg_neg_reg_1077_pp0_iter10 = ap_reg_ppstg_neg_reg_1077_pp0_iter9.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter11 = ap_reg_ppstg_neg_reg_1077_pp0_iter10.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter12 = ap_reg_ppstg_neg_reg_1077_pp0_iter11.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter13 = ap_reg_ppstg_neg_reg_1077_pp0_iter12.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter14 = ap_reg_ppstg_neg_reg_1077_pp0_iter13.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter15 = ap_reg_ppstg_neg_reg_1077_pp0_iter14.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter16 = ap_reg_ppstg_neg_reg_1077_pp0_iter15.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter17 = ap_reg_ppstg_neg_reg_1077_pp0_iter16.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter18 = ap_reg_ppstg_neg_reg_1077_pp0_iter17.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter19 = ap_reg_ppstg_neg_reg_1077_pp0_iter18.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter2 = ap_reg_ppstg_neg_reg_1077_pp0_iter1.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter20 = ap_reg_ppstg_neg_reg_1077_pp0_iter19.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter3 = ap_reg_ppstg_neg_reg_1077_pp0_iter2.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter4 = ap_reg_ppstg_neg_reg_1077_pp0_iter3.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter5 = ap_reg_ppstg_neg_reg_1077_pp0_iter4.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter6 = ap_reg_ppstg_neg_reg_1077_pp0_iter5.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter7 = ap_reg_ppstg_neg_reg_1077_pp0_iter6.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter8 = ap_reg_ppstg_neg_reg_1077_pp0_iter7.read();
        ap_reg_ppstg_neg_reg_1077_pp0_iter9 = ap_reg_ppstg_neg_reg_1077_pp0_iter8.read();
        ap_reg_ppstg_p_1_reg_1091_pp0_iter2 = ap_reg_ppstg_p_1_reg_1091_pp0_iter1.read();
        ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2 = tmp_416_reg_1121.read();
        ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3 = tmp_427_reg_1156.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter10 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter9.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter11 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter10.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter12 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter11.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter13 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter12.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter14 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter13.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter15 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter14.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter16 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter15.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter17 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter16.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter18 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter17.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter19 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter18.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter20 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter19.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter3 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter4 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter3.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter5 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter4.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter6 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter5.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter7 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter6.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter8 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter7.read();
        ap_reg_ppstg_tmp_s_reg_1087_pp0_iter9 = ap_reg_ppstg_tmp_s_reg_1087_pp0_iter8.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter3.read(), ap_const_lv1_0))) {
        coscos_V_reg_1209 = p_Val2_6_fu_997_p2.read().range(17, 2);
        cossin_V_reg_1204 = p_Val2_5_fu_981_p2.read().range(17, 2);
        sincos_V_reg_1194 = p_Val2_3_fu_931_p2.read().range(17, 2);
        sinsin_V_reg_1199 = p_Val2_4_fu_961_p2.read().range(17, 2);
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_416_reg_1121.read()))) {
        mf15_3_reg_1145 = mf15_3_fu_566_p2.read();
        mf_3_reg_1140 = mf_3_fu_556_p2.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_427_reg_1156.read()))) {
        mf15_5_reg_1179 = mf15_5_fu_834_p2.read();
        mf_5_reg_1174 = mf_5_fu_828_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(tmp_s_fu_209_p2.read(), ap_const_lv1_0))) {
        p_1_reg_1091 = p_1_fu_257_p3.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter1.read(), ap_const_lv1_0))) {
        p_Val2_111_2_reg_1128 = p_Val2_111_2_fu_499_p2.read();
        p_Val2_114_2_reg_1134 = p_Val2_114_2_fu_550_p2.read();
        tmp_422_reg_1150 = p_Val2_116_3_fu_600_p2.read().range(18, 18);
        tmp_427_reg_1156 = p_Val2_116_4_fu_644_p2.read().range(18, 18);
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter2.read(), ap_const_lv1_0))) {
        p_Val2_111_4_reg_1162 = p_Val2_111_4_fu_779_p2.read();
        p_Val2_114_4_reg_1168 = p_Val2_114_4_fu_822_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(tmp_s_reg_1087.read(), ap_const_lv1_0))) {
        p_Val2_116_2_reg_1116 = p_Val2_116_2_fu_393_p2.read();
        tmp_408_reg_1097 = theta_in_V_assign_fu_272_p2.read().range(15, 15);
        tmp_409_reg_1104 = p_Val2_46_fu_305_p2.read().range(18, 18);
        tmp_410_reg_1110 = p_Val2_116_1_fu_349_p2.read().range(18, 18);
        tmp_416_reg_1121 = p_Val2_116_2_fu_393_p2.read().range(18, 18);
    }
}

void svm_classifier_getTanh::thread_OP1_V_1_cast_fu_977_p1() {
    OP1_V_1_cast_fu_977_p1 = esl_zext<19,9>(cosh_lut_V_q0.read());
}

void svm_classifier_getTanh::thread_OP1_V_cast_fu_923_p1() {
    OP1_V_cast_fu_923_p1 = esl_zext<19,9>(sinh_lut_V_q0.read());
}

void svm_classifier_getTanh::thread_OP2_V_18_1_fu_414_p3() {
    OP2_V_18_1_fu_414_p3 = (!tmp_408_reg_1097.read()[0].is_01())? sc_lv<11>(): ((tmp_408_reg_1097.read()[0].to_bool())? ap_const_lv11_595: ap_const_lv11_26A);
}

void svm_classifier_getTanh::thread_OP2_V_19_2_cast_fu_505_p1() {
    OP2_V_19_2_cast_fu_505_p1 = esl_zext<14,13>(p_Val2_111_1_fu_439_p2.read());
}

void svm_classifier_getTanh::thread_OP2_V_19_3_cast_cast_fu_562_p1() {
    OP2_V_19_3_cast_cast_fu_562_p1 = esl_zext<14,13>(p_Val2_111_2_fu_499_p2.read());
}

void svm_classifier_getTanh::thread_OP2_V_1_cast_fu_957_p1() {
    OP2_V_1_cast_fu_957_p1 = esl_sext<19,10>(tmp_28_fu_947_p4.read());
}

void svm_classifier_getTanh::thread_OP2_V_cast_fu_927_p1() {
    OP2_V_cast_fu_927_p1 = esl_sext<19,10>(tmp_25_fu_913_p4.read());
}

void svm_classifier_getTanh::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it21.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it21.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1() {
    ap_reg_phiprechg_p_Val2_11_reg_176pp0_it1 =  (sc_lv<8>) ("XXXXXXXX");
}

void svm_classifier_getTanh::thread_ap_reg_ppiten_pp0_it0() {
    ap_reg_ppiten_pp0_it0 = ap_start.read();
}

void svm_classifier_getTanh::thread_ap_return() {
    ap_return = (!ap_reg_ppstg_neg_reg_1077_pp0_iter20.read()[0].is_01())? sc_lv<8>(): ((ap_reg_ppstg_neg_reg_1077_pp0_iter20.read()[0].to_bool())? p_Val2_47_fu_1064_p2.read(): p_Val2_11_phi_fu_180_p4.read());
}

void svm_classifier_getTanh::thread_ap_sig_18() {
    ap_sig_18 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void svm_classifier_getTanh::thread_ap_sig_311() {
    ap_sig_311 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)));
}

void svm_classifier_getTanh::thread_ap_sig_cseq_ST_pp0_stg0_fsm_0() {
    if (ap_sig_18.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_ap_sig_pprstidle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ppiten_pp0_it20.read()))) {
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    } else {
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_cosh_lut_V_address0() {
    cosh_lut_V_address0 =  (sc_lv<3>) (tmp_23_fu_840_p1.read());
}

void svm_classifier_getTanh::thread_cosh_lut_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        cosh_lut_V_ce0 = ap_const_logic_1;
    } else {
        cosh_lut_V_ce0 = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_cosh_out_V_fu_1021_p4() {
    cosh_out_V_fu_1021_p4 = tmp_305_fu_1017_p2.read().range(14, 7);
}

void svm_classifier_getTanh::thread_grp_fu_1053_p0() {
    grp_fu_1053_p0 = esl_concat<8,5>(tmp_306_fu_1031_p4.read(), ap_const_lv5_0);
}

void svm_classifier_getTanh::thread_mf15_2_fu_509_p2() {
    mf15_2_fu_509_p2 = (!ap_const_lv14_0.is_01() || !OP2_V_19_2_cast_fu_505_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(OP2_V_19_2_cast_fu_505_p1.read()));
}

void svm_classifier_getTanh::thread_mf15_3_fu_566_p2() {
    mf15_3_fu_566_p2 = (!ap_const_lv14_0.is_01() || !OP2_V_19_3_cast_cast_fu_562_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(OP2_V_19_3_cast_cast_fu_562_p1.read()));
}

void svm_classifier_getTanh::thread_mf15_4_fu_785_p2() {
    mf15_4_fu_785_p2 = (!ap_const_lv15_0.is_01() || !p_Val2_111_3_fu_693_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_biguint<15>(p_Val2_111_3_fu_693_p2.read()));
}

void svm_classifier_getTanh::thread_mf15_5_fu_834_p2() {
    mf15_5_fu_834_p2 = (!ap_const_lv15_0.is_01() || !p_Val2_111_4_fu_779_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_biguint<15>(p_Val2_111_4_fu_779_p2.read()));
}

void svm_classifier_getTanh::thread_mf_1_fu_421_p3() {
    mf_1_fu_421_p3 = (!tmp_408_reg_1097.read()[0].is_01())? sc_lv<11>(): ((tmp_408_reg_1097.read()[0].to_bool())? ap_const_lv11_26A: ap_const_lv11_596);
}

void svm_classifier_getTanh::thread_mf_2_fu_462_p2() {
    mf_2_fu_462_p2 = (!ap_const_lv13_0.is_01() || !p_Val2_114_1_fu_452_p2.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_biguint<13>(p_Val2_114_1_fu_452_p2.read()));
}

void svm_classifier_getTanh::thread_mf_3_fu_556_p2() {
    mf_3_fu_556_p2 = (!ap_const_lv14_0.is_01() || !p_Val2_114_2_fu_550_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(p_Val2_114_2_fu_550_p2.read()));
}

void svm_classifier_getTanh::thread_mf_4_fu_742_p2() {
    mf_4_fu_742_p2 = (!ap_const_lv15_0.is_01() || !p_Val2_114_3_fu_736_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_biguint<15>(p_Val2_114_3_fu_736_p2.read()));
}

void svm_classifier_getTanh::thread_mf_5_fu_828_p2() {
    mf_5_fu_828_p2 = (!ap_const_lv15_0.is_01() || !p_Val2_114_4_fu_822_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_biguint<15>(p_Val2_114_4_fu_822_p2.read()));
}

void svm_classifier_getTanh::thread_neg_fu_187_p3() {
    neg_fu_187_p3 = theta_in_V.read().range(15, 15);
}

void svm_classifier_getTanh::thread_p_1_fu_257_p3() {
    p_1_fu_257_p3 = (!tmp_406_fu_225_p3.read()[0].is_01())? sc_lv<7>(): ((tmp_406_fu_225_p3.read()[0].to_bool())? p_s_fu_249_p3.read(): ret_V_fu_215_p4.read());
}

void svm_classifier_getTanh::thread_p_Val2_111_1_fu_439_p2() {
    p_Val2_111_1_fu_439_p2 = (!ap_const_lv13_1351.is_01() || !tmp_127_1_cast_fu_435_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(ap_const_lv13_1351) + sc_bigint<13>(tmp_127_1_cast_fu_435_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_111_2_cast2_fu_658_p1() {
    p_Val2_111_2_cast2_fu_658_p1 = esl_zext<15,13>(p_Val2_111_2_reg_1128.read());
}

void svm_classifier_getTanh::thread_p_Val2_111_2_fu_499_p2() {
    p_Val2_111_2_fu_499_p2 = (!p_Val2_111_1_fu_439_p2.read().is_01() || !tmp_1304_2_cast_fu_495_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_Val2_111_1_fu_439_p2.read()) + sc_bigint<13>(tmp_1304_2_cast_fu_495_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_111_3_fu_693_p2() {
    p_Val2_111_3_fu_693_p2 = (!p_Val2_111_2_cast2_fu_658_p1.read().is_01() || !tmp_1304_3_cast_fu_689_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_111_2_cast2_fu_658_p1.read()) + sc_bigint<15>(tmp_1304_3_cast_fu_689_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_111_4_fu_779_p2() {
    p_Val2_111_4_fu_779_p2 = (!p_Val2_111_3_fu_693_p2.read().is_01() || !tmp_1304_4_cast_fu_775_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_111_3_fu_693_p2.read()) + sc_bigint<15>(tmp_1304_4_cast_fu_775_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_111_5_fu_874_p2() {
    p_Val2_111_5_fu_874_p2 = (!p_Val2_111_4_reg_1162.read().is_01() || !tmp_1304_5_cast_fu_870_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_111_4_reg_1162.read()) + sc_bigint<15>(tmp_1304_5_cast_fu_870_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_114_1_cast_cast_fu_458_p1() {
    p_Val2_114_1_cast_cast_fu_458_p1 = esl_sext<14,13>(p_Val2_114_1_fu_452_p2.read());
}

void svm_classifier_getTanh::thread_p_Val2_114_1_fu_452_p2() {
    p_Val2_114_1_fu_452_p2 = (!tmp_385_fu_407_p3.read().is_01() || !tmp_1356_1_cast_cast_fu_445_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_385_fu_407_p3.read()) + sc_biguint<13>(tmp_1356_1_cast_cast_fu_445_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_114_2_cast1_fu_661_p1() {
    p_Val2_114_2_cast1_fu_661_p1 = esl_sext<15,14>(p_Val2_114_2_reg_1134.read());
}

void svm_classifier_getTanh::thread_p_Val2_114_2_fu_550_p2() {
    p_Val2_114_2_fu_550_p2 = (!p_Val2_114_1_cast_cast_fu_458_p1.read().is_01() || !tmp_1356_2_cast_fu_546_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(p_Val2_114_1_cast_cast_fu_458_p1.read()) + sc_bigint<14>(tmp_1356_2_cast_fu_546_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_114_3_fu_736_p2() {
    p_Val2_114_3_fu_736_p2 = (!p_Val2_114_2_cast1_fu_661_p1.read().is_01() || !tmp_1356_3_cast_fu_732_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(p_Val2_114_2_cast1_fu_661_p1.read()) + sc_bigint<15>(tmp_1356_3_cast_fu_732_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_114_4_fu_822_p2() {
    p_Val2_114_4_fu_822_p2 = (!p_Val2_114_3_fu_736_p2.read().is_01() || !tmp_1356_4_cast_fu_818_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_114_3_fu_736_p2.read()) + sc_bigint<15>(tmp_1356_4_cast_fu_818_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_114_5_fu_908_p2() {
    p_Val2_114_5_fu_908_p2 = (!p_Val2_114_4_reg_1168.read().is_01() || !tmp_1356_5_cast_fu_904_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_114_4_reg_1168.read()) + sc_bigint<15>(tmp_1356_5_cast_fu_904_p1.read()));
}

void svm_classifier_getTanh::thread_p_Val2_116_1_fu_349_p2() {
    p_Val2_116_1_fu_349_p2 = (!tmp_140_1_cast_fu_337_p1.read().is_01() || !tmp_1418_1_cast_cast_fu_341_p3.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_140_1_cast_fu_337_p1.read()) - sc_biguint<21>(tmp_1418_1_cast_cast_fu_341_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_116_2_fu_393_p2() {
    p_Val2_116_2_fu_393_p2 = (!tmp_140_2_cast_fu_381_p1.read().is_01() || !tmp_1418_2_cast_cast_fu_385_p3.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_140_2_cast_fu_381_p1.read()) - sc_biguint<21>(tmp_1418_2_cast_cast_fu_385_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_116_3_fu_600_p2() {
    p_Val2_116_3_fu_600_p2 = (!tmp_140_3_cast_fu_589_p1.read().is_01() || !tmp_1418_3_cast_cast_fu_593_p3.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_140_3_cast_fu_589_p1.read()) - sc_biguint<21>(tmp_1418_3_cast_cast_fu_593_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_116_4_fu_644_p2() {
    p_Val2_116_4_fu_644_p2 = (!tmp_140_4_cast_fu_632_p1.read().is_01() || !tmp_1418_4_cast_cast_fu_636_p3.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_140_4_cast_fu_632_p1.read()) - sc_biguint<21>(tmp_1418_4_cast_cast_fu_636_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_11_phi_fu_180_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it21.read()) && 
         !esl_seteq<1,1,1>(ap_reg_ppstg_tmp_s_reg_1087_pp0_iter20.read(), ap_const_lv1_0))) {
        p_Val2_11_phi_fu_180_p4 = pro_V_fu_1059_p1.read();
    } else {
        p_Val2_11_phi_fu_180_p4 = ap_reg_phiprechg_p_Val2_11_reg_176pp0_it21.read();
    }
}

void svm_classifier_getTanh::thread_p_Val2_3_fu_931_p0() {
    p_Val2_3_fu_931_p0 =  (sc_lv<10>) (OP2_V_cast_fu_927_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_3_fu_931_p1() {
    p_Val2_3_fu_931_p1 =  (sc_lv<9>) (OP1_V_cast_fu_923_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_46_fu_305_p2() {
    p_Val2_46_fu_305_p2 = (!tmp_140_cast_fu_293_p1.read().is_01() || !tmp_450_cast_cast_fu_297_p3.read().is_01())? sc_lv<21>(): (sc_bigint<21>(tmp_140_cast_fu_293_p1.read()) - sc_biguint<21>(tmp_450_cast_cast_fu_297_p3.read()));
}

void svm_classifier_getTanh::thread_p_Val2_47_fu_1064_p2() {
    p_Val2_47_fu_1064_p2 = (!ap_const_lv8_0.is_01() || !p_Val2_11_phi_fu_180_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_0) - sc_biguint<8>(p_Val2_11_phi_fu_180_p4.read()));
}

void svm_classifier_getTanh::thread_p_Val2_4_fu_961_p0() {
    p_Val2_4_fu_961_p0 =  (sc_lv<10>) (OP2_V_1_cast_fu_957_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_4_fu_961_p1() {
    p_Val2_4_fu_961_p1 =  (sc_lv<9>) (OP1_V_cast_fu_923_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_5_fu_981_p0() {
    p_Val2_5_fu_981_p0 =  (sc_lv<10>) (OP2_V_1_cast_fu_957_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_5_fu_981_p1() {
    p_Val2_5_fu_981_p1 =  (sc_lv<9>) (OP1_V_1_cast_fu_977_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_6_fu_997_p0() {
    p_Val2_6_fu_997_p0 =  (sc_lv<10>) (OP2_V_cast_fu_927_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_6_fu_997_p1() {
    p_Val2_6_fu_997_p1 =  (sc_lv<9>) (OP1_V_1_cast_fu_977_p1.read());
}

void svm_classifier_getTanh::thread_p_Val2_s_54_fu_201_p3() {
    p_Val2_s_54_fu_201_p3 = (!neg_fu_187_p3.read()[0].is_01())? sc_lv<16>(): ((neg_fu_187_p3.read()[0].to_bool())? p_Val2_s_fu_195_p2.read(): theta_in_V.read());
}

void svm_classifier_getTanh::thread_p_Val2_s_fu_195_p2() {
    p_Val2_s_fu_195_p2 = (!ap_const_lv16_0.is_01() || !theta_in_V.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(theta_in_V.read()));
}

void svm_classifier_getTanh::thread_p_s_fu_249_p3() {
    p_s_fu_249_p3 = (!tmp_20_fu_237_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_20_fu_237_p2.read()[0].to_bool())? ret_V_fu_215_p4.read(): ret_V_1_fu_243_p2.read());
}

void svm_classifier_getTanh::thread_p_v1_fu_811_p3() {
    p_v1_fu_811_p3 = (!tmp_422_reg_1150.read()[0].is_01())? sc_lv<11>(): ((tmp_422_reg_1150.read()[0].to_bool())? tmp_426_fu_801_p4.read(): tmp_425_fu_791_p4.read());
}

void svm_classifier_getTanh::thread_p_v2_fu_863_p3() {
    p_v2_fu_863_p3 = (!ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3.read()[0].is_01())? sc_lv<10>(): ((ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3.read()[0].to_bool())? tmp_429_fu_854_p4.read(): tmp_428_fu_845_p4.read());
}

void svm_classifier_getTanh::thread_p_v3_fu_897_p3() {
    p_v3_fu_897_p3 = (!ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3.read()[0].is_01())? sc_lv<10>(): ((ap_reg_ppstg_tmp_427_reg_1156_pp0_iter3.read()[0].to_bool())? tmp_431_fu_888_p4.read(): tmp_430_fu_879_p4.read());
}

void svm_classifier_getTanh::thread_p_v9_fu_768_p3() {
    p_v9_fu_768_p3 = (!tmp_422_reg_1150.read()[0].is_01())? sc_lv<11>(): ((tmp_422_reg_1150.read()[0].to_bool())? tmp_424_fu_758_p4.read(): tmp_423_fu_748_p4.read());
}

void svm_classifier_getTanh::thread_p_v_fu_682_p3() {
    p_v_fu_682_p3 = (!ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2.read()[0].is_01())? sc_lv<10>(): ((ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2.read()[0].to_bool())? tmp_418_fu_673_p4.read(): tmp_417_fu_664_p4.read());
}

void svm_classifier_getTanh::thread_pro_V_fu_1059_p1() {
    pro_V_fu_1059_p1 = grp_fu_1053_p2.read().range(8-1, 0);
}

void svm_classifier_getTanh::thread_ret_V_1_fu_243_p2() {
    ret_V_1_fu_243_p2 = (!ap_const_lv7_1.is_01() || !ret_V_fu_215_p4.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(ret_V_fu_215_p4.read()));
}

void svm_classifier_getTanh::thread_ret_V_fu_215_p4() {
    ret_V_fu_215_p4 = p_Val2_s_54_fu_201_p3.read().range(15, 9);
}

void svm_classifier_getTanh::thread_sinh_lut_V_address0() {
    sinh_lut_V_address0 =  (sc_lv<3>) (tmp_23_fu_840_p1.read());
}

void svm_classifier_getTanh::thread_sinh_lut_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        sinh_lut_V_ce0 = ap_const_logic_1;
    } else {
        sinh_lut_V_ce0 = ap_const_logic_0;
    }
}

void svm_classifier_getTanh::thread_theta_in_V_assign_fu_272_p2() {
    theta_in_V_assign_fu_272_p2 = (!p_Val2_s_54_reg_1082.read().is_01() || !tmp_22_fu_265_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_Val2_s_54_reg_1082.read()) - sc_biguint<16>(tmp_22_fu_265_p3.read()));
}

void svm_classifier_getTanh::thread_tmp_127_1_cast_fu_435_p1() {
    tmp_127_1_cast_fu_435_p1 = esl_sext<13,11>(tmp_127_1_fu_428_p3.read());
}

void svm_classifier_getTanh::thread_tmp_127_1_fu_428_p3() {
    tmp_127_1_fu_428_p3 = (!tmp_409_reg_1104.read()[0].is_01())? sc_lv<11>(): ((tmp_409_reg_1104.read()[0].to_bool())? mf_1_fu_421_p3.read(): OP2_V_18_1_fu_414_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1304_2_cast_fu_495_p1() {
    tmp_1304_2_cast_fu_495_p1 = esl_sext<13,10>(tmp_413_fu_488_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1304_3_cast_fu_689_p1() {
    tmp_1304_3_cast_fu_689_p1 = esl_sext<15,10>(p_v_fu_682_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1304_4_cast_fu_775_p1() {
    tmp_1304_4_cast_fu_775_p1 = esl_sext<15,11>(p_v9_fu_768_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1304_5_cast_fu_870_p1() {
    tmp_1304_5_cast_fu_870_p1 = esl_sext<15,10>(p_v2_fu_863_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1356_1_cast_cast_fu_445_p3() {
    tmp_1356_1_cast_cast_fu_445_p3 = (!tmp_409_reg_1104.read()[0].is_01())? sc_lv<13>(): ((tmp_409_reg_1104.read()[0].to_bool())? ap_const_lv13_1B2B: ap_const_lv13_4D4);
}

void svm_classifier_getTanh::thread_tmp_1356_2_cast_fu_546_p1() {
    tmp_1356_2_cast_fu_546_p1 = esl_sext<14,11>(tmp_415_fu_539_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1356_3_cast_fu_732_p1() {
    tmp_1356_3_cast_fu_732_p1 = esl_sext<15,13>(tmp_421_fu_725_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1356_4_cast_fu_818_p1() {
    tmp_1356_4_cast_fu_818_p1 = esl_sext<15,11>(p_v1_fu_811_p3.read());
}

void svm_classifier_getTanh::thread_tmp_1356_5_cast_fu_904_p1() {
    tmp_1356_5_cast_fu_904_p1 = esl_sext<15,10>(p_v3_fu_897_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_1_cast_fu_337_p1() {
    tmp_140_1_cast_fu_337_p1 = esl_sext<21,19>(tmp_140_1_fu_329_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_1_fu_329_p3() {
    tmp_140_1_fu_329_p3 = esl_concat<16,3>(tmp_269_fu_319_p4.read(), ap_const_lv3_0);
}

void svm_classifier_getTanh::thread_tmp_140_2_cast_fu_381_p1() {
    tmp_140_2_cast_fu_381_p1 = esl_sext<21,19>(tmp_140_2_fu_373_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_2_fu_373_p3() {
    tmp_140_2_fu_373_p3 = esl_concat<16,3>(tmp_277_fu_363_p4.read(), ap_const_lv3_0);
}

void svm_classifier_getTanh::thread_tmp_140_3_cast_fu_589_p1() {
    tmp_140_3_cast_fu_589_p1 = esl_sext<21,19>(tmp_140_3_fu_581_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_3_fu_581_p3() {
    tmp_140_3_fu_581_p3 = esl_concat<16,3>(tmp_286_fu_572_p4.read(), ap_const_lv3_0);
}

void svm_classifier_getTanh::thread_tmp_140_4_cast_fu_632_p1() {
    tmp_140_4_cast_fu_632_p1 = esl_sext<21,19>(tmp_140_4_fu_624_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_4_fu_624_p3() {
    tmp_140_4_fu_624_p3 = esl_concat<16,3>(tmp_295_fu_614_p4.read(), ap_const_lv3_0);
}

void svm_classifier_getTanh::thread_tmp_140_cast_fu_293_p1() {
    tmp_140_cast_fu_293_p1 = esl_sext<21,19>(tmp_140_fu_285_p3.read());
}

void svm_classifier_getTanh::thread_tmp_140_fu_285_p3() {
    tmp_140_fu_285_p3 = esl_concat<16,3>(theta_in_V_assign_fu_272_p2.read(), ap_const_lv3_0);
}

void svm_classifier_getTanh::thread_tmp_1418_1_cast_cast_fu_341_p3() {
    tmp_1418_1_cast_cast_fu_341_p3 = (!tmp_409_fu_311_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_409_fu_311_p3.read()[0].to_bool())? ap_const_lv21_7FBEA: ap_const_lv21_416);
}

void svm_classifier_getTanh::thread_tmp_1418_2_cast_cast_fu_385_p3() {
    tmp_1418_2_cast_cast_fu_385_p3 = (!tmp_410_fu_355_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_410_fu_355_p3.read()[0].to_bool())? ap_const_lv21_7FDFE: ap_const_lv21_202);
}

void svm_classifier_getTanh::thread_tmp_1418_3_cast_cast_fu_593_p3() {
    tmp_1418_3_cast_cast_fu_593_p3 = (!tmp_416_reg_1121.read()[0].is_01())? sc_lv<21>(): ((tmp_416_reg_1121.read()[0].to_bool())? ap_const_lv21_7FF00: ap_const_lv21_100);
}

void svm_classifier_getTanh::thread_tmp_1418_4_cast_cast_fu_636_p3() {
    tmp_1418_4_cast_cast_fu_636_p3 = (!tmp_422_fu_606_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_422_fu_606_p3.read()[0].to_bool())? ap_const_lv21_7FF00: ap_const_lv21_100);
}

void svm_classifier_getTanh::thread_tmp_20_fu_237_p2() {
    tmp_20_fu_237_p2 = (!tmp_407_fu_233_p1.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_407_fu_233_p1.read() == ap_const_lv9_0);
}

void svm_classifier_getTanh::thread_tmp_22_fu_265_p3() {
    tmp_22_fu_265_p3 = esl_concat<7,9>(p_1_reg_1091.read(), ap_const_lv9_0);
}

void svm_classifier_getTanh::thread_tmp_23_fu_840_p1() {
    tmp_23_fu_840_p1 = esl_sext<64,7>(ap_reg_ppstg_p_1_reg_1091_pp0_iter2.read());
}

void svm_classifier_getTanh::thread_tmp_25_fu_913_p4() {
    tmp_25_fu_913_p4 = p_Val2_111_5_fu_874_p2.read().range(13, 4);
}

void svm_classifier_getTanh::thread_tmp_269_fu_319_p4() {
    tmp_269_fu_319_p4 = p_Val2_46_fu_305_p2.read().range(18, 3);
}

void svm_classifier_getTanh::thread_tmp_273_fu_515_p4() {
    tmp_273_fu_515_p4 = p_Val2_111_1_fu_439_p2.read().range(12, 3);
}

void svm_classifier_getTanh::thread_tmp_274_fu_525_p1() {
    tmp_274_fu_525_p1 = esl_zext<11,10>(tmp_273_fu_515_p4.read());
}

void svm_classifier_getTanh::thread_tmp_277_fu_363_p4() {
    tmp_277_fu_363_p4 = p_Val2_116_1_fu_349_p2.read().range(18, 3);
}

void svm_classifier_getTanh::thread_tmp_283_fu_708_p1() {
    tmp_283_fu_708_p1 = esl_zext<13,9>(tmp_419_fu_699_p4.read());
}

void svm_classifier_getTanh::thread_tmp_284_fu_721_p1() {
    tmp_284_fu_721_p1 = esl_sext<13,10>(tmp_420_fu_712_p4.read());
}

void svm_classifier_getTanh::thread_tmp_286_fu_572_p4() {
    tmp_286_fu_572_p4 = p_Val2_116_2_reg_1116.read().range(18, 3);
}

void svm_classifier_getTanh::thread_tmp_28_fu_947_p4() {
    tmp_28_fu_947_p4 = p_Val2_114_5_fu_908_p2.read().range(13, 4);
}

void svm_classifier_getTanh::thread_tmp_295_fu_614_p4() {
    tmp_295_fu_614_p4 = p_Val2_116_3_fu_600_p2.read().range(18, 3);
}

void svm_classifier_getTanh::thread_tmp_304_fu_1013_p2() {
    tmp_304_fu_1013_p2 = (!sincos_V_reg_1194.read().is_01() || !cossin_V_reg_1204.read().is_01())? sc_lv<16>(): (sc_biguint<16>(sincos_V_reg_1194.read()) + sc_biguint<16>(cossin_V_reg_1204.read()));
}

void svm_classifier_getTanh::thread_tmp_305_fu_1017_p2() {
    tmp_305_fu_1017_p2 = (!sinsin_V_reg_1199.read().is_01() || !coscos_V_reg_1209.read().is_01())? sc_lv<16>(): (sc_biguint<16>(sinsin_V_reg_1199.read()) + sc_biguint<16>(coscos_V_reg_1209.read()));
}

void svm_classifier_getTanh::thread_tmp_306_fu_1031_p4() {
    tmp_306_fu_1031_p4 = tmp_304_fu_1013_p2.read().range(14, 7);
}

void svm_classifier_getTanh::thread_tmp_385_fu_407_p3() {
    tmp_385_fu_407_p3 = (!tmp_408_reg_1097.read()[0].is_01())? sc_lv<13>(): ((tmp_408_reg_1097.read()[0].to_bool())? ap_const_lv13_1657: ap_const_lv13_9A8);
}

void svm_classifier_getTanh::thread_tmp_406_fu_225_p3() {
    tmp_406_fu_225_p3 = p_Val2_s_54_fu_201_p3.read().range(15, 15);
}

void svm_classifier_getTanh::thread_tmp_407_fu_233_p1() {
    tmp_407_fu_233_p1 = p_Val2_s_54_fu_201_p3.read().range(9-1, 0);
}

void svm_classifier_getTanh::thread_tmp_408_fu_277_p3() {
    tmp_408_fu_277_p3 = theta_in_V_assign_fu_272_p2.read().range(15, 15);
}

void svm_classifier_getTanh::thread_tmp_409_fu_311_p3() {
    tmp_409_fu_311_p3 = p_Val2_46_fu_305_p2.read().range(18, 18);
}

void svm_classifier_getTanh::thread_tmp_410_fu_355_p3() {
    tmp_410_fu_355_p3 = p_Val2_116_1_fu_349_p2.read().range(18, 18);
}

void svm_classifier_getTanh::thread_tmp_411_fu_468_p4() {
    tmp_411_fu_468_p4 = mf_2_fu_462_p2.read().range(12, 3);
}

void svm_classifier_getTanh::thread_tmp_412_fu_478_p4() {
    tmp_412_fu_478_p4 = p_Val2_114_1_fu_452_p2.read().range(12, 3);
}

void svm_classifier_getTanh::thread_tmp_413_fu_488_p3() {
    tmp_413_fu_488_p3 = (!tmp_410_reg_1110.read()[0].is_01())? sc_lv<10>(): ((tmp_410_reg_1110.read()[0].to_bool())? tmp_411_fu_468_p4.read(): tmp_412_fu_478_p4.read());
}

void svm_classifier_getTanh::thread_tmp_414_fu_529_p4() {
    tmp_414_fu_529_p4 = mf15_2_fu_509_p2.read().range(13, 3);
}

void svm_classifier_getTanh::thread_tmp_415_fu_539_p3() {
    tmp_415_fu_539_p3 = (!tmp_410_reg_1110.read()[0].is_01())? sc_lv<11>(): ((tmp_410_reg_1110.read()[0].to_bool())? tmp_414_fu_529_p4.read(): tmp_274_fu_525_p1.read());
}

void svm_classifier_getTanh::thread_tmp_417_fu_664_p4() {
    tmp_417_fu_664_p4 = p_Val2_114_2_reg_1134.read().range(13, 4);
}

void svm_classifier_getTanh::thread_tmp_418_fu_673_p4() {
    tmp_418_fu_673_p4 = mf_3_reg_1140.read().range(13, 4);
}

void svm_classifier_getTanh::thread_tmp_419_fu_699_p4() {
    tmp_419_fu_699_p4 = p_Val2_111_2_reg_1128.read().range(12, 4);
}

void svm_classifier_getTanh::thread_tmp_420_fu_712_p4() {
    tmp_420_fu_712_p4 = mf15_3_reg_1145.read().range(13, 4);
}

void svm_classifier_getTanh::thread_tmp_421_fu_725_p3() {
    tmp_421_fu_725_p3 = (!ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2.read()[0].is_01())? sc_lv<13>(): ((ap_reg_ppstg_tmp_416_reg_1121_pp0_iter2.read()[0].to_bool())? tmp_284_fu_721_p1.read(): tmp_283_fu_708_p1.read());
}

void svm_classifier_getTanh::thread_tmp_422_fu_606_p3() {
    tmp_422_fu_606_p3 = p_Val2_116_3_fu_600_p2.read().range(18, 18);
}

void svm_classifier_getTanh::thread_tmp_423_fu_748_p4() {
    tmp_423_fu_748_p4 = p_Val2_114_3_fu_736_p2.read().range(14, 4);
}

void svm_classifier_getTanh::thread_tmp_424_fu_758_p4() {
    tmp_424_fu_758_p4 = mf_4_fu_742_p2.read().range(14, 4);
}

void svm_classifier_getTanh::thread_tmp_425_fu_791_p4() {
    tmp_425_fu_791_p4 = p_Val2_111_3_fu_693_p2.read().range(14, 4);
}

void svm_classifier_getTanh::thread_tmp_426_fu_801_p4() {
    tmp_426_fu_801_p4 = mf15_4_fu_785_p2.read().range(14, 4);
}

void svm_classifier_getTanh::thread_tmp_428_fu_845_p4() {
    tmp_428_fu_845_p4 = p_Val2_114_4_reg_1168.read().range(14, 5);
}

void svm_classifier_getTanh::thread_tmp_429_fu_854_p4() {
    tmp_429_fu_854_p4 = mf_5_reg_1174.read().range(14, 5);
}

void svm_classifier_getTanh::thread_tmp_430_fu_879_p4() {
    tmp_430_fu_879_p4 = p_Val2_111_4_reg_1162.read().range(14, 5);
}

void svm_classifier_getTanh::thread_tmp_431_fu_888_p4() {
    tmp_431_fu_888_p4 = mf15_5_reg_1179.read().range(14, 5);
}

void svm_classifier_getTanh::thread_tmp_450_cast_cast_fu_297_p3() {
    tmp_450_cast_cast_fu_297_p3 = (!tmp_408_fu_277_p3.read()[0].is_01())? sc_lv<21>(): ((tmp_408_fu_277_p3.read()[0].to_bool())? ap_const_lv21_7F737: ap_const_lv21_8C9);
}

void svm_classifier_getTanh::thread_tmp_s_fu_209_p2() {
    tmp_s_fu_209_p2 = (!p_Val2_s_54_fu_201_p3.read().is_01() || !ap_const_lv16_A00.is_01())? sc_lv<1>(): (sc_bigint<16>(p_Val2_s_54_fu_201_p3.read()) < sc_bigint<16>(ap_const_lv16_A00));
}

void svm_classifier_getTanh::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

