// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_H__
#define __svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 13;
  static const unsigned AddressRange = 116;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_ram) {
        for (unsigned i = 0; i < 6 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[6] = "0b1110111101011";
        ram[7] = "0b0000010000101";
        ram[8] = "0b1110111101011";
        for (unsigned i = 9; i < 15 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[15] = "0b1001011111110";
        ram[16] = "0b0000010000101";
        ram[17] = "0b0000010000101";
        ram[18] = "0b0000010000101";
        ram[19] = "0b0000010000101";
        ram[20] = "0b1100100111101";
        ram[21] = "0b0000010000101";
        ram[22] = "0b1111011110101";
        for (unsigned i = 23; i < 36 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[36] = "0b1111001110000";
        ram[37] = "0b1111011110101";
        for (unsigned i = 38; i < 44 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[44] = "0b1111101111010";
        ram[45] = "0b1111011110101";
        ram[46] = "0b0000010000101";
        ram[47] = "0b0000010000101";
        ram[48] = "0b0000010000101";
        ram[49] = "0b0000010000101";
        ram[50] = "0b1111101111010";
        for (unsigned i = 51; i < 58 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[58] = "0b1111101111010";
        for (unsigned i = 59; i < 73 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[73] = "0b1111101111010";
        ram[74] = "0b0000010000101";
        ram[75] = "0b1110101100110";
        ram[76] = "0b1110111101011";
        ram[77] = "0b0000010000101";
        ram[78] = "0b0000010000101";
        ram[79] = "0b0000010000101";
        ram[80] = "0b0000010000101";
        ram[81] = "0b1111101111010";
        for (unsigned i = 82; i < 87 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[87] = "0b1001110000101";
        ram[88] = "0b0000010000101";
        ram[89] = "0b1111011110101";
        for (unsigned i = 90; i < 106 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[106] = "0b1111011110101";
        for (unsigned i = 107; i < 116 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(svm_classifier_Loop_Sum_loop_proc1_alpha_V_7) {


static const unsigned DataWidth = 13;
static const unsigned AddressRange = 116;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_ram* meminst;


SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_7) {
meminst = new svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_ram("svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~svm_classifier_Loop_Sum_loop_proc1_alpha_V_7() {
    delete meminst;
}


};//endmodule
#endif
