// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_H__
#define __svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 13;
  static const unsigned AddressRange = 117;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_ram) {
        ram[0] = "0b1001011111110";
        for (unsigned i = 1; i < 15 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[15] = "0b1111101111010";
        ram[16] = "0b0000010000101";
        ram[17] = "0b0000010000101";
        ram[18] = "0b0000010000101";
        ram[19] = "0b0000010000101";
        ram[20] = "0b1111011110101";
        ram[21] = "0b0000010000101";
        ram[22] = "0b0000010000101";
        ram[23] = "0b0000010000101";
        ram[24] = "0b1100000111100";
        ram[25] = "0b0000010000101";
        ram[26] = "0b0000010000101";
        ram[27] = "0b0000010000101";
        ram[28] = "0b1111011110101";
        ram[29] = "0b0000010000101";
        ram[30] = "0b0000010000101";
        ram[31] = "0b1111101111010";
        ram[32] = "0b0000010000101";
        ram[33] = "0b0000010000101";
        ram[34] = "0b0000010000101";
        ram[35] = "0b0000010000101";
        ram[36] = "0b1101101010001";
        ram[37] = "0b0000010000101";
        ram[38] = "0b0000010000101";
        ram[39] = "0b0000010000101";
        ram[40] = "0b0000010000101";
        ram[41] = "0b1110101100110";
        for (unsigned i = 42; i < 51 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[51] = "0b1111101111010";
        for (unsigned i = 52; i < 60 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[60] = "0b1111011110101";
        for (unsigned i = 61; i < 72 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[72] = "0b1111101111010";
        for (unsigned i = 73; i < 79 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[79] = "0b1111101111010";
        ram[80] = "0b1010000001010";
        ram[81] = "0b0000010000101";
        ram[82] = "0b0000010000101";
        ram[83] = "0b0000010000101";
        ram[84] = "0b1111101111010";
        ram[85] = "0b0000010000101";
        ram[86] = "0b1111011110101";
        ram[87] = "0b0000010000101";
        ram[88] = "0b0000010000101";
        ram[89] = "0b0000010000101";
        ram[90] = "0b0000010000101";
        ram[91] = "0b1010110011011";
        for (unsigned i = 92; i < 103 ; i = i + 1) {
            ram[i] = "0b0000010000101";
        }
        ram[103] = "0b1111001110000";
        ram[104] = "0b0000010000101";
        ram[105] = "0b1110011100001";
        ram[106] = "0b1111101111010";
        ram[107] = "0b0000010000101";
        ram[108] = "0b0000010000101";
        ram[109] = "0b0000010000101";
        ram[110] = "0b1111011110101";
        ram[111] = "0b1111101111010";
        ram[112] = "0b0000010000101";
        ram[113] = "0b0000010000101";
        ram[114] = "0b1111011110101";
        ram[115] = "0b0000010000101";
        ram[116] = "0b0000010000101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(svm_classifier_Loop_Sum_loop_proc1_alpha_V_2) {


static const unsigned DataWidth = 13;
static const unsigned AddressRange = 117;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_ram* meminst;


SC_CTOR(svm_classifier_Loop_Sum_loop_proc1_alpha_V_2) {
meminst = new svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_ram("svm_classifier_Loop_Sum_loop_proc1_alpha_V_2_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~svm_classifier_Loop_Sum_loop_proc1_alpha_V_2() {
    delete meminst;
}


};//endmodule
#endif
