// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "in_V"
#define AUTOTB_TVIN_in_V  "../tv/cdatafile/c.svm_classifier.autotvin_in_V.dat"
// wrapc file define: "out_r"
#define AUTOTB_TVOUT_out_r  "../tv/cdatafile/c.svm_classifier.autotvout_out_r.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "out_r"
#define AUTOTB_TVOUT_PC_out_r  "../tv/rtldatafile/rtl.svm_classifier.autotvout_out_r.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			in_V_depth = 0;
			out_r_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{in_V " << in_V_depth << "}\n";
			total_list << "{out_r " << out_r_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int in_V_depth;
		int out_r_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define svm_classifier AESL_ORIG_DUT_svm_classifier
extern void svm_classifier (
ap_fixed<16, 4, (ap_q_mode) 5, (ap_o_mode)3, 0> in[16],
bool* out);
#undef svm_classifier

void svm_classifier (
ap_fixed<16, 4, (ap_q_mode) 5, (ap_o_mode)3, 0> in[16],
bool* out)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "out_r"
		aesl_fh.read(AUTOTB_TVOUT_PC_out_r, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_out_r, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_out_r, AESL_token); // data

			sc_bv<1> *out_r_pc_buffer = new sc_bv<1>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'out_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					out_r_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_out_r, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_out_r))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: out_r
				{
					// bitslice(0, 0)
					// {
						// celement: out(0, 0)
						// {
							sc_lv<1>* out_lv0_0_0_1 = new sc_lv<1>[1];
						// }
					// }

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out(0, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(out[0]) != NULL) // check the null address if the c port is array or others
								{
									out_lv0_0_0_1[hls_map_index++].range(0, 0) = sc_bv<1>(out_r_pc_buffer[hls_map_index].range(0, 0));
								}
							}
						}
					}

					// bitslice(0, 0)
					{
						int hls_map_index = 0;
						// celement: out(0, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : out[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : out[0]
								// output_left_conversion : out[i_0]
								// output_type_conversion : (out_lv0_0_0_1[hls_map_index++]).to_uint64()
								if (&(out[0]) != NULL) // check the null address if the c port is array or others
								{
									out[i_0] = (out_lv0_0_0_1[hls_map_index++]).to_uint64();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] out_r_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "in_V"
		char* tvin_in_V = new char[69];
		aesl_fh.touch(AUTOTB_TVIN_in_V);

		// "out_r"
		char* tvout_out_r = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_out_r);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_in_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_in_V, tvin_in_V);

		sc_bv<256>* in_V_tvin_wrapc_buffer = new sc_bv<256>[1];

		// RTL Name: in_V
		{
			// bitslice(15, 0)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (0) => (0) @ (2)
					for (int i_0 = 0; i_0 <= 0; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(15, 0) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(31, 16)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (1) => (1) @ (2)
					for (int i_0 = 1; i_0 <= 1; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(31, 16) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(47, 32)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (2) => (2) @ (2)
					for (int i_0 = 2; i_0 <= 2; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(47, 32) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(63, 48)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (3) => (3) @ (2)
					for (int i_0 = 3; i_0 <= 3; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(63, 48) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(79, 64)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (4) => (4) @ (2)
					for (int i_0 = 4; i_0 <= 4; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(79, 64) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(95, 80)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (5) => (5) @ (2)
					for (int i_0 = 5; i_0 <= 5; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(95, 80) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(111, 96)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (6) => (6) @ (2)
					for (int i_0 = 6; i_0 <= 6; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(111, 96) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(127, 112)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (7) => (7) @ (2)
					for (int i_0 = 7; i_0 <= 7; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(127, 112) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(143, 128)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (8) => (8) @ (2)
					for (int i_0 = 8; i_0 <= 8; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(143, 128) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(159, 144)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (9) => (9) @ (2)
					for (int i_0 = 9; i_0 <= 9; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(159, 144) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(175, 160)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (10) => (10) @ (2)
					for (int i_0 = 10; i_0 <= 10; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(175, 160) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(191, 176)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (11) => (11) @ (2)
					for (int i_0 = 11; i_0 <= 11; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(191, 176) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(207, 192)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (12) => (12) @ (2)
					for (int i_0 = 12; i_0 <= 12; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(207, 192) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(223, 208)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (13) => (13) @ (2)
					for (int i_0 = 13; i_0 <= 13; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(223, 208) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(239, 224)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (14) => (14) @ (2)
					for (int i_0 = 14; i_0 <= 14; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(239, 224) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
			// bitslice(255, 240)
			{
				int hls_map_index = 0;
				// celement: in.V(15, 0)
				{
					// carray: (15) => (15) @ (2)
					for (int i_0 = 15; i_0 <= 15; i_0 += 2)
					{
						// sub                   : i_0
						// ori_name              : in[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in[0]
						// regulate_c_name       : in_V
						// input_type_conversion : (in[i_0]).range().to_string(SC_BIN).c_str()
						if (&(in[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> in_V_tmp_mem;
							in_V_tmp_mem = (in[i_0]).range().to_string(SC_BIN).c_str();
							in_V_tvin_wrapc_buffer[hls_map_index++].range(255, 240) = in_V_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_in_V, "%s\n", (in_V_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_in_V, tvin_in_V);
		}

		tcl_file.set_num(1, &tcl_file.in_V_depth);
		sprintf(tvin_in_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_in_V, tvin_in_V);

		// release memory allocation
		delete [] in_V_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		AESL_ORIG_DUT_svm_classifier(in, out);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_out_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_out_r, tvout_out_r);

		sc_bv<1>* out_r_tvout_wrapc_buffer = new sc_bv<1>[1];

		// RTL Name: out_r
		{
			// bitslice(0, 0)
			{
				int hls_map_index = 0;
				// celement: out(0, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : out[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : out[0]
						// regulate_c_name       : out
						// input_type_conversion : out[i_0]
						if (&(out[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> out_tmp_mem;
							out_tmp_mem = out[i_0];
							out_r_tvout_wrapc_buffer[hls_map_index++].range(0, 0) = out_tmp_mem.range(0, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_out_r, "%s\n", (out_r_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_out_r, tvout_out_r);
		}

		tcl_file.set_num(1, &tcl_file.out_r_depth);
		sprintf(tvout_out_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_out_r, tvout_out_r);

		// release memory allocation
		delete [] out_r_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "in_V"
		delete [] tvin_in_V;
		// release memory allocation: "out_r"
		delete [] tvout_out_r;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

