-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity svm_classifier_Loop_Sum_loop_proc1_alpha_V_4_rom is 
    generic(
             dwidth     : integer := 13; 
             awidth     : integer := 7; 
             mem_size    : integer := 117
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of svm_classifier_Loop_Sum_loop_proc1_alpha_V_4_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "0000010000101", 1 => "1110101100111", 2 to 11=> "0000010000101", 
    12 => "1111101111010", 13 to 16=> "0000010000101", 17 => "1111101111010", 
    18 to 29=> "0000010000101", 30 => "1111101111010", 31 => "1111011110101", 
    32 to 35=> "0000010000101", 36 => "1111001110000", 37 to 45=> "0000010000101", 
    46 => "1111001110000", 47 => "0000010000101", 48 => "1110111101011", 
    49 to 50=> "0000010000101", 51 => "1111101111010", 52 => "0000010000101", 
    53 => "1111001110000", 54 to 61=> "0000010000101", 62 => "1001011111110", 
    63 to 65=> "0000010000101", 66 => "1111101111010", 67 to 73=> "0000010000101", 
    74 => "1111101111010", 75 => "1001011111110", 76 to 78=> "0000010000101", 
    79 => "1110101100110", 80 to 84=> "0000010000101", 85 => "1101101010001", 
    86 => "1110111101011", 87 to 93=> "0000010000101", 94 => "1111011110101", 
    95 to 107=> "0000010000101", 108 => "1111011110101", 109 to 110=> "0000010000101", 
    111 => "1111101111010", 112 to 116=> "0000010000101" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity svm_classifier_Loop_Sum_loop_proc1_alpha_V_4 is
    generic (
        DataWidth : INTEGER := 13;
        AddressRange : INTEGER := 117;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of svm_classifier_Loop_Sum_loop_proc1_alpha_V_4 is
    component svm_classifier_Loop_Sum_loop_proc1_alpha_V_4_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    svm_classifier_Loop_Sum_loop_proc1_alpha_V_4_rom_U :  component svm_classifier_Loop_Sum_loop_proc1_alpha_V_4_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


