-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_rom is 
    generic(
             dwidth     : integer := 13; 
             awidth     : integer := 7; 
             mem_size    : integer := 116
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 5=> "0000010000101", 6 => "1110111101011", 7 => "0000010000101", 
    8 => "1110111101011", 9 to 14=> "0000010000101", 15 => "1001011111110", 
    16 to 19=> "0000010000101", 20 => "1100100111101", 21 => "0000010000101", 
    22 => "1111011110101", 23 to 35=> "0000010000101", 36 => "1111001110000", 
    37 => "1111011110101", 38 to 43=> "0000010000101", 44 => "1111101111010", 
    45 => "1111011110101", 46 to 49=> "0000010000101", 50 => "1111101111010", 
    51 to 57=> "0000010000101", 58 => "1111101111010", 59 to 72=> "0000010000101", 
    73 => "1111101111010", 74 => "0000010000101", 75 => "1110101100110", 
    76 => "1110111101011", 77 to 80=> "0000010000101", 81 => "1111101111010", 
    82 to 86=> "0000010000101", 87 => "1001110000101", 88 => "0000010000101", 
    89 => "1111011110101", 90 to 105=> "0000010000101", 106 => "1111011110101", 
    107 to 115=> "0000010000101" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity svm_classifier_Loop_Sum_loop_proc1_alpha_V_7 is
    generic (
        DataWidth : INTEGER := 13;
        AddressRange : INTEGER := 116;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of svm_classifier_Loop_Sum_loop_proc1_alpha_V_7 is
    component svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_rom_U :  component svm_classifier_Loop_Sum_loop_proc1_alpha_V_7_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


