# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.cache/wt [current_project]
set_property parent.project_path H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths h:/MATLAB/MATLAB_2/MATLAB/svm_classifier_prj_v6.2_Ch18/svm_classifier_prj_v6.2_Ch18/svm_classifier_prj/svm_classifier_prj/solution1/impl [current_project]
add_files H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_svm_classifier_0_0/constraints/svm_classifier_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib H:/MATLAB/MATLAB_2/MATLAB/svm_vivado/project_5_dataflow/project_5_dataflow.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
